### ISSUE TITLE
No operations completed within the last ### seconds. There are still # rpcs and # retries in progress.

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#1013]
Under certain circumstances, usually either a networking glitch or prolonged periods of overloading a Cloud Bigtable cluster, there will be failures with individual RPCs out of a large batch write job.  When that happens, an RPC fails to report its status back to RpcThrottler.

RPCThrottler ensures that not too many RPCs are sent.  At the end of a job, it's responsible to ensure that all RPCs complete.  A failure to report completion is an extremely rare occurrence, but it happens under large batch jobs that cause the RPC's completion to go unrecorded.  That seems to happen most when there is a queue of RPCs that are waiting to be sent on a single Netty Channel.

At the end of the job, the RpcThrottler thinks the RPC is still active, and the job does not complete.

There needs to be better handling of ensuring that the RPC is managed correctly (perhaps canceled and retried, or somehow get the status of the gRPC ClientCall).  For now, there are a couple things a user can do:
1. Update to the latest client, which may have a gRPC fixes.
2. Over provision Bigtable for the duration of the job to reduce the likelihood of the problem

**Comment by sduskis** [comment]
We made some changes.  #1067, #1068, #1069 which seemed to have fixed this.  We have a test that would choke on this problem every other time we ran it.  After #1069, we were able to run a dozen or so times without fail.  We'll keep an eye on the test for another day.  If this isn't a problem anymore, I'll close this, call this bug fixed.

**Comment by sduskis** [comment]
We were able to reproduce this problem reliably, and after the fixes we haven't seen this problem.

**Comment by dlahlou** [comment]
I'm still having the same problem when trying to insert raws in different Bigtable tables simultaneously using saveAsNewAPIHadoopDataset under spark (scala).

**Comment by pabloem** [comment]
can you share which versions are affected by this issue?
