### ISSUE TITLE
Reusing an existing Codahale MetricRegistry?

### ISSUE THREAD

**Issue by pcarrier** [GoogleCloudPlatform/cloud-bigtable-client#1047]
https://cloud.google.com/bigtable/docs/hbase-metrics mentions the use of Codahale Metrics that third-party reporters are available.

However those third-party reporters tend to integrate with `com.codahale.metrics.MetricRegistry`, not `com.google.cloud.bigtable.metrics.MetricRegistry`.

Am I missing an obvious way to bridge that gap?

**Comment by sduskis** [comment]
The intention is to allow different  implementations of com.google.cloud.bigtable.metrics.MetricRegistry.  Some of our users have different implementations of metrics gathering frameworks.  I'm guessing that we'll integrate with [Census](https://github.com/google/census-java) soon enough.
