### ISSUE TITLE
Sources reachable by build tools, IDEs, etc.?

### ISSUE THREAD

**Issue by pcarrier** [GoogleCloudPlatform/cloud-bigtable-client#1048]
After adding the `compile 'com.google.cloud.bigtable:bigtable-hbase-1.2'` dependency, IntelliJ, Gradle, etc. cannot find sources JAR.

I'm hoping this is enough information, please let me know if I should try to better illustrate the problem /dig into the issue.

**Comment by pcarrier** [comment]
```
% curl -sf 'http://repo1.maven.org/maven2/com/google/cloud/bigtable/bigtable-hbase-1.2/0.9.3/bigtable-hbase-1.2-0.9.3-sources.jar'|bsdtar tf -
META-INF/MANIFEST.MF
META-INF/
com/
com/google/
com/google/cloud/
com/google/cloud/bigtable/
com/google/cloud/bigtable/hbase1_2/
com/google/cloud/bigtable/hbase/
META-INF/maven/
META-INF/maven/com.google.cloud.bigtable/
META-INF/maven/com.google.cloud.bigtable/bigtable-hbase-1.2/
com/google/cloud/bigtable/hbase1_2/BigtableConnection.java
com/google/cloud/bigtable/hbase/bigtable-hbase.properties
META-INF/maven/com.google.cloud.bigtable/bigtable-hbase-1.2/pom.xml
META-INF/maven/com.google.cloud.bigtable/bigtable-hbase-1.2/pom.properties
```

**Comment by sduskis** [comment]
We do some wild renaming of packages with the [shade plugin ](https://maven.apache.org/plugins/maven-shade-plugin/)so that we can work both in the hadoop/hbase ecosystem and the Dataflow.

In maven, I have to do a "mvn install" to get everything to work properly.

**Comment by pcarrier** [comment]
Is it not a goal to provide a good developer experience or is fixing this problem too unrealistic to be tracked as a Github issue?

**Comment by sduskis** [comment]
It's a great goal.  It unfortunately lower than making things work.  We need the package renaming logic to work in both hadoop/hbase environments and Dataflow environments.  It sucks.  I'll reopen this to see if there's a way improve the experience.

**Comment by sduskis** [comment]
try: `curl -sf 'http://repo1.maven.org/maven2/com/google/cloud/bigtable/bigtable-hbase/0.9.3/bigtable-hbase-0.9.3-sources.jar'|bsdtar tf -`

**Comment by igorbernstein2** [comment]
We've introduced bigtable-hbase-1.x, which no longer requires shading and should avoid the missing source issues

**Comment by guillaumecle** [comment]
I'm not sure to understand how the last comment solve this ticket: from the beginning this ticket is about "bigtable-hbase-1.2"

**Comment by sduskis** [comment]
bigtable-hbase-1.2 is being deprecated in favor of bigtable-hbase-1.x.  The approach taken for -1.0, -1.1, -1.2 and -1.3 jars had a fundamental flaw that boils down to package renaming due to versioning issues relating to "dll hell" or more precisely "transitive dependency hell".  We had to do quite a bit of changes in our dependencies to fix that deep rooted problem. We were concerned about backwards compatibility with the 1.[0-3], so we wanted to keep them as is.  We opted to solve the spirit of this request by creating a new single artifact that is a drop in replacement for the 1.[0-3] set of artifacts that did not require us to perform package renaming in our artifacts.

**Comment by igorbernstein** [comment]
My apologies, I should've been more clear.  We are introducing 3 new artifacts that are replacing the old bigtable-hbase-{shaded,1.0,1.1,1.2,1.3}. 

The new artifacts are:

- bigtable-hbase-1.x: depends on hbase-shaded-client and exposes grpc and modern version of protobuf. This artifact is meant for standalone usage in webapps, beam, and other environments where the user is in control of their dependencies. This contains the actual connection implementation for hbase 1. It doesn't require any shading and allows for source navigation in ides. This should be the default choice for most users.

- bigtable-hbase-1.x-shaded: this artifact doesn't contain any java source files, but uses the maven shade plugin to relocate all internal dependencies. This is meant for environments where the user is not in control of their dependencies and is mostly an implementation detail for dataflow 1.x that will eventually be deprecated in favor of beam.  Source navigation will be partially broken for this artifact: you will be able to navigate to the hbase connector code, but navigation to the underlying core client will be broken. However this is just a stopgap measure until we transition to beam. 
- bigtable-hbase-1.x-hadoop: this is similar the -shaded variant but exposes Hadoop compatible dependencies. This is meant to be used in mapreduce jobs where the mapreduce framework injects jars into the user'a classpath. This will have similar limitations as the -shaded variant: you will be able to navigate to hbase compatibility code, but not the underlying core client. Unfortunately I don't think this is something we can do anything about. I would appreciate any suggestions.

Which of these environments are you concerned about?

**Comment by guillaumecle** [comment]
Thank you for the details. I'm concerned about a webapp context.
So bigtable-hbase-1.x (with an actual x letter in the name?) is a new artifact that will arrive soon on maven central?
Is their a documentation where all the publish artifacts (currently 12) are listed and their usage is documented?

**Comment by igorbernstein2** [comment]
Yes, literally [bigtable-hbase-1.x](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/tree/master/bigtable-hbase-parent/bigtable-hbase-1.x), it will be available in maven central once we finish polishing the release. Once its released, you will be able to switch to it and never have to be concerned about shading issues.

Documentation is one of the things that needs to be updated for the upcoming release. And you are right we do have too many artifacts, here is a summary of them:

The 3 artifacts I mentioned above and bigtable-hbase-dataflow are the main artifacts that are intended for public consumption. 

List of other artifacts:
- bigtable-hbase-dataflow: bigtable connector for dataflow 1.x using the hbase api
- bigtable-dataflow-import: is meant to be a cli utility to enable importing & exporting hbase sequence files to/from bigtable using dataflow
- bigtable-hbase-mapreduce: is meant to be a cli utility to enable importing & exporting hbase sequence files to/from bigtable using hadoop/mapreduce
- bigtable-hbase: is an internal artifact not meant for public consumption it contains/will contain common code for hbase 1 & 2 apis
- bigtable-hbase-shaded, bigtable-hbase-1.0, bigtable-hbase-1.1, bigtable-hbase-1.2, bigtable-hbase-1.3: Will be deprecated as of the next release and will be deleted in the following release.
- bigtable-client-core is the low level client that exposes its own undocumented api that hasn't stabilized yet and thus we discourage direct usage of it.
- bigtable-protos: auto generated protobufs and grpc wrappers
