### ISSUE TITLE
How to authenticate and get a Connection instance, from credentials in a JSON string?

### ISSUE THREAD

**Issue by mgoddard-pivotal** [GoogleCloudPlatform/cloud-bigtable-client#1206]
I am working on accessing Bigtable from Cloud Foundry, using a new version of the [GCP service broker](https://github.com/GoogleCloudPlatform/gcp-service-broker).  When an application is bound to an instance of this service,  credentials are passed in via an environment variable, and the service account JSON credentials are accessible here.  When using PubSub, we can get a PubSub client like this:

```
PubSub pubSub = PubSubOptions.newBuilder().setProjectId(projectId).setCredentials(cred).build().getService();
```

where `cred` comes from an InputStream from our JSON string:

```
Credentials cred = ServiceAccountCredentials.fromStream(in);
```

This is handy in such an environment, and we have been able to find similar, although not identical, approaches in the following Google Cloud Platform APIs: Vision, BigQuery, and Storage.  So far, I don't see how we can do this using the Bigtable Java client API, and am just seeking advice on this.

**Comment by sduskis** [comment]
Can you set a GOOGLE_APPLICATION_CREDENTIALS variable as per the [default credentials handling](https://developers.google.com/identity/protocols/application-default-credentials)?

**Comment by sduskis** [comment]
We do have the ability for you to set a credentials object in the CredentialsOptions, if you're using the BigtableSession object.  Most users use the HBase API, and I'm guessing you're using it as well.  We have the constraint of working with HBase's configuration mechanism over Hadoop.

I need to add a JSon file option for the HBase configuration option.

**Comment by mgoddard-pivotal** [comment]
Thanks for adding that comment.  For our purposes, HBase isn't special in any way, though I understand the HBase client makes sense as folks would have experience with HBase, probably.  There's no Hadoop involved here, just Bigtable (we're not migrating away from HBase).

Can you point to any examples of starting with a BigtableSession and getting a Connection, from which you are able to interact with Bigtable to create tables and insert/update/delete data?  Such an example would be very helpful here.

**Comment by sduskis** [comment]
We don't currently have documentation or examples of BigtableSession, for a variety of reasons.  BigtableSession is equivalent to a Connection, and has "admin clients" and a "data client" on which operations are performed.

```
BigtableSession session = new BigtableSession(new BigtableOptions.Builder()
  .setProjectId(project)
  .setInstanceId(instance)
  .setCredentialOptions(CredentialOptions.credential(credentials)
).build());

BigtableDataClient dataClient = session.getDataClient()
...
```

If you want to go this route, instead of working with the HBase option, we should discuss this offline (maybe set up with Dana?).

The standard GOOGLE_APPLICATION_CREDENTIALS environment variable is still an option via the HBase API.  I'll also add an option for setting json files in the HBase configuration in a future release.

**Comment by sduskis** [comment]
If you have a file, the following HBase approach would already 

```
  Configuration config = BigtableConfiguration.configur(projectId, instanceId);
  config.set("google.bigtable.auth.json.keyfile", "/your/file.json");
  Connection conn = BigtableConfiguration.connect(config);
```

**Comment by mgoddard-pivotal** [comment]
Thanks, Solomon.  I do have a code variant where I write out that JSON to a file in /tmp and then set the environment variable, within the Java code, to point to this file.  I'm sure that'll work here, too.

**Comment by mgoddard-pivotal** [comment]
That approach was like this:
```
   String gcpJsonFromEnv = System.getenv("GOOGLE_APPLICATION_CREDENTIALS");
   File gcpJsonFile = new File(System.getProperty("java.io.tmpdir"), "GCP_credentials.json");
   if (gcpJsonFromEnv != null && gcpJsonFromEnv.startsWith("{")) {
      PrintWriter out = new PrintWriter(gcpJsonFile);
      out.println(gcpJsonFromEnv);
      out.close();
      Map<String, String> replEnv = new HashMap<>();
      replEnv.put("GOOGLE_APPLICATION_CREDENTIALS", gcpJsonFile.getPath());
      setEnv(replEnv);
   }
```
Where `setEnv` (taken from StackOverflow) looks like:
```
private static void setEnv(Map<String, String> newenv)
  {
  try
    {
      Class<?> processEnvironmentClass = Class.forName("java.lang.ProcessEnvironment");
      Field theEnvironmentField = processEnvironmentClass.getDeclaredField("theEnvironment");
      theEnvironmentField.setAccessible(true);
      Map<String, String> env = (Map<String, String>) theEnvironmentField.get(null);
      env.putAll(newenv);
      Field theCaseInsensitiveEnvironmentField = processEnvironmentClass.getDeclaredField("theCaseInsensitiveEnvironment");
      theCaseInsensitiveEnvironmentField.setAccessible(true);
      Map<String, String> cienv = (Map<String, String>) theCaseInsensitiveEnvironmentField.get(null);
      cienv.putAll(newenv);
    }
    catch (NoSuchFieldException e)
    {
      try {
        Class[] classes = Collections.class.getDeclaredClasses();
        Map<String, String> env = System.getenv();
        for(Class cl : classes) {
            if("java.util.Collections$UnmodifiableMap".equals(cl.getName())) {
                Field field = cl.getDeclaredField("m");
                field.setAccessible(true);
                Object obj = field.get(env);
                Map<String, String> map = (Map<String, String>) obj;
                map.clear();
                map.putAll(newenv);
            }
        }
      } catch (Exception e2) {
        e2.printStackTrace();
      }
    } catch (Exception e1) {
        e1.printStackTrace();
    }
  }
```

**Comment by mahmoudhanafy** [comment]
@sduskis Why there is no documentation for `BigtableSession` ? Is it safe to be used ?
Is it possible to read the JSON credentials file as a String and pass it to HBase client ?
