### ISSUE TITLE
Bigtable HBase Exports are actually not compatible with HBase

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#1231]
Exports from Bigtable are no longer compatible with HBase.  The culprit is [`RowCell`](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/read/RowCell.java) which is a performance optimization for Cloud Bigtable scans.  It replaces HBase's [`KeyValue`](https://github.com/apache/hbase/blob/master/hbase-common/src/main/java/org/apache/hadoop/hbase/KeyValue.java) which is a great wire protocol, but caused performance bottlenecks for general Cloud Bigtable scans.

The solution is to translate `RowCell`s to `KeyValue` cells in the export process.  Bonus: have an option in the export process to allow `RowCell` for more performant disaster recovery backups.

**Comment by igorbernstein2** [comment]
I don't think this is the case...they get converted into the same protobuf:

https://github.com/apache/hbase/blob/rel/1.2.4/hbase-server/src/main/java/org/apache/hadoop/hbase/mapreduce/ResultSerialization.java#L155

https://github.com/apache/hbase/blob/rel/1.2.4/hbase-client/src/main/java/org/apache/hadoop/hbase/protobuf/ProtobufUtil.java#L1366

https://github.com/apache/hbase/blob/rel/1.2.4/hbase-client/src/main/java/org/apache/hadoop/hbase/protobuf/ProtobufUtil.java#L2551

I think this can be safely closed
