### ISSUE TITLE
Concurrent modification exceptions using CloudBigtableIO

### ISSUE THREAD

**Issue by ankurcha** [GoogleCloudPlatform/cloud-bigtable-client#1244]
While long running (streaming) dataflow job on our production dataset I saw some exceptions in the worker logs (about 200).

```java
Exception: java.util.ConcurrentModificationException
java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
java.util.HashMap$ValueIterator.next(HashMap.java:1466)
com.google.bigtable.repackaged.com.google.cloud.grpc.async.RpcThrottler.awaitCompletion(RpcThrottler.java:177)
com.google.bigtable.repackaged.com.google.cloud.grpc.async.AsyncExecutor.flush(AsyncExecutor.java:330)
com.google.bigtable.repackaged.com.google.cloud.hbase.BigtableBufferedMutator.flush(BigtableBufferedMutator.java:236)
com.google.bigtable.repackaged.com.google.cloud.hbase.BigtableBufferedMutator.close(BigtableBufferedMutator.java:213)
org.apache.hadoop.hbase.client.AbstractBigtableConnection$2.close(AbstractBigtableConnection.java:181)
com.google.cloud.bigtable.dataflow.CloudBigtableIO$CloudBigtableSingleTableBufferedWriteFn.finishBundle(CloudBigtableIO.java:989)
```

It seems like the `RpcThrottler#awaitCompletion` is being called for multiple bundles at the same time from multiple worker threads. I saw there is a `@GuardedBy("lock")` annotation at the declaration site but looks like that's not catching the condition here.

* Connector version `0.9.5.1`

**Comment by sduskis** [comment]
Ugh.  I'll fix this for 0.9.6.  I'll add a lock around the iteration.

**Comment by sduskis** [comment]
wait a second... this shouldn't happen.  There should only be one call to CloudBigtableSingleTableBufferedWriteFn.finishBundle().  How did you set up that scenario?

**Comment by sduskis** [comment]
I should probably make CloudBigtableSingleTableBufferedWriteFn.finishBundle() final, but I'm really confused about why I need to do that.

**Comment by garye** [comment]
I think `RpcThrottler#awaitCompletion` can handle multiple concurrent calls. But that retry code at line 177 can end up calling into `onRetryCompletion` and removing from `outstandingRetries` which would cause the exception.

**Comment by 4d55397500** [comment]
I'm also experiencing this problem with 0.9.5. When will 0.9.6 be released? Until then which stable release is suggested?
