### ISSUE TITLE
Unrelocated dropwizard metrics classes in client jar

### ISSUE THREAD

**Issue by ckolbeck** [GoogleCloudPlatform/cloud-bigtable-client#1257]
Version: 0.9.5.1
Artifact: bigtable-hbase-1.2

Howdy, we're running into some issues with duplicate checking during builds due to what looks like the contents of io.dropwizard.metrics:metrics-core present in the jar at the usual com/codahale/metrics path. While it looks like it should be version 3.1.2 based on the pom, maven is reporting bytecode differences for all files with the maven central v3.1.2.

Was this intentional? While we can get around it easily enough, based on the heavy use of relocation for other dependencies it seems odd. 

Thanks,
Cory

**Comment by sduskis** [comment]
I poked around at this problem, but couldn't find a quick fix for this problem.  I'm going to have to think about how to remove our dependency on dropwizard in the core project.  I might opt to use Google's new `instrumentation-java` package instead of dropwizard as the default implementation, and allow for dropwizard as an alternative.

**Comment by ckolbeck** [comment]
Is relocating them not an option, similar to how other 3rd party deps are being handled?

**Comment by sduskis** [comment]
It's an option, but it's not trivial.  Relocating would break compatibility with other dropwizard integrations.  Some customers use graphite, and that integration would break if I do a simple relocation.

I think that this is an important issue to address in the near term.  I plan on a release early next week, and I don't think that the solution to the problem can be addressed by Tuesday of next week.

**Comment by ckolbeck** [comment]
Definitely. Thanks a bunch for looking into it, and in the meantime we can do the needful to get a clean build.

**Comment by ckolbeck** [comment]
Would you like me to leave this open or close it?

**Comment by sduskis** [comment]
Please leave this open.  It's important that this issue gets resolved one way or another.

**Comment by igorbernstein2** [comment]
dropwizard is no longer shaded in the 1.x artifacts

**Comment by ckolbeck** [comment]
Thank you for your work.

**Comment by christophsturm** [comment]
i just.downloaded the com.google.cloud.bigtable:bigtable-hbase-1.2:1.0.0-pre1 jar and it still contains codahale metrics. (and commons-lang, and asm and some others)

**Comment by sduskis** [comment]
Please use bigtable-hbase-1**.x**:1.0.0-pre1 instead.  The 1.x (with an explicit "x") artifact is going to replace the 1.0, 1.1, 1.2 and 1.3 artifacts.

**Comment by igorbernstein2** [comment]
Hi,

We still need to update the docs. We didn't update bigtable-hbase-1.0, 1.1, etc. Instead we introduced 3 new artifacts replacing the old bigtable-hbase-{shaded,1.0,1.1,1.2,1.3}. Please switch to one of the new 1.x variants. None of them shade dropwizard metrics. All of the older artifacts are being deprecated

The new artifacts are:

- bigtable-hbase-1.x: depends on hbase-shaded-client and exposes grpc and modern version of protobuf. This artifact is meant for standalone usage in webapps, beam, and other environments where the user is in control of their dependencies. This contains the actual connection implementation for hbase 1. It doesn't require any shading and allows for source navigation in ides. This should be the default choice for most users.

- bigtable-hbase-1.x-shaded: this artifact doesn't contain any java source files, but uses the maven shade plugin to relocate all internal dependencies. This is meant for environments where the user is not in control of their dependencies and is mostly an implementation detail for dataflow 1.x that will eventually be deprecated in favor of beam. Source navigation will be partially broken for this artifact: you will be able to navigate to the hbase connector code, but navigation to the underlying core client will be broken. However this is just a stopgap measure until we transition to beam.

- bigtable-hbase-1.x-hadoop: this is similar the -shaded variant but exposes Hadoop compatible dependencies. This is meant to be used in mapreduce jobs where the mapreduce framework injects jars into the user'a classpath. This will have similar limitations as the -shaded variant: you will be able to navigate to hbase compatibility code, but not the underlying core client. Unfortunately I don't think this is something we can do anything about. I would appreciate any suggestions.

**Comment by christophsturm** [comment]
thanks!

**Comment by srosenberg** [comment]
Please note that `bigtable-hbase-1.2:1.0.0-pre1` _now_ requires these explicit runtime dependencies 

* commons-configuration
* hadoop-auth

owing to ` org.apache.hadoop.hbase.client.ConnectionFactory.createConnection`.  See stack traces below,

```
java.lang.NoClassDefFoundError: org/apache/commons/configuration/Configuration
        at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.<init>(DefaultMetricsSystem.java:38)
        at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.<clinit>(DefaultMetricsSystem.java:36)
        at org.apache.hadoop.security.UserGroupInformation$UgiMetrics.create(UserGroupInformation.java:108)
        at org.apache.hadoop.security.UserGroupInformation.<clinit>(UserGroupInformation.java:210)
        at org.apache.hadoop.hbase.security.User$SecureHadoopUser.<init>(User.java:293)
        at org.apache.hadoop.hbase.security.User.getCurrent(User.java:191)
        at org.apache.hadoop.hbase.security.UserProvider.getCurrent(UserProvider.java:167)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:215)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
```

```
java.lang.NoClassDefFoundError: org/apache/hadoop/util/PlatformName
        at org.apache.hadoop.security.UserGroupInformation.getOSLoginModuleName(UserGroupInformation.java:339)
        at org.apache.hadoop.security.UserGroupInformation.<clinit>(UserGroupInformation.java:384)
        at org.apache.hadoop.hbase.security.User$SecureHadoopUser.<init>(User.java:293)
        at org.apache.hadoop.hbase.security.User.getCurrent(User.java:191)
        at org.apache.hadoop.hbase.security.UserProvider.getCurrent(UserProvider.java:167)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:215)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
```

**Comment by sduskis** [comment]
I opened #1439 to fix this issue.

**Comment by srosenberg** [comment]
@sduskis  I ran into another issue with `bigtable-hbase-1.x-shaded`.  It depends on `hbase-shaded-client:1.3.1` whose jar includes unshaded Hadoop classes, e.g., 

```
jar tvf /Users/srosenberg/.gradle/caches/modules-2/files-2.1/org.apache.hbase/hbase-shaded-client/1.3.1/9cfc06ed28de61a25a47b02af1bed1007fdbed2e/hbase-shaded-client-1.3.1.jar |grep ConfigUtil
  2369 Thu Apr 06 19:57:00 EDT 2017 org/apache/hadoop/fs/viewfs/ConfigUtil.class
 21841 Thu Apr 06 19:57:02 EDT 2017 org/apache/hadoop/mapreduce/util/ConfigUtil.class
```

Thus, if `bigtable-hbase-1.x-shaded` happens to be first on the classpath, it will most likely conflict with incompatible versions of hadoop/spark as it did in my case.

**Comment by igorbernstein2** [comment]
Hi @srosenberg,

Please use `bigtable-hbase-1.x-hadoop`. It depends on the unshaded hbase-client 1.3.1.
