### ISSUE TITLE
[Question] [HBase Client] ValueFilter adapter for BinaryComparator with CompareOp.EQUAL

### ISSUE THREAD

**Issue by ckolbeck** [GoogleCloudPlatform/cloud-bigtable-client#1264]
Relevant code: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/filters/ValueFilterAdapter.java#L80

The use of `ValueRegexFilter` here seems odd, and currently breaks against the emulator if the value contains non-UTF8 bytes. That fact is well documented, but not documented is the fact that `BigtableTable.checkAndPut()` is implemented using a ValueRegexFilter, causing operations which expect non-UTF8 byte strings to always silently fail against the emulator.

Is there a reason to use a `ValueRegexFilter` here instead of a `ValueRange` with closed upper and lower bounds of the desired value?

**Comment by sduskis** [comment]
Good catch.  PR is forthcoming.

**Comment by ckolbeck** [comment]
Wonderful! Thanks so much for the quick work. Do you think this will make it in to next weeks release that you mentioned in https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/1257?

**Comment by sduskis** [comment]
This should make it in for next week's release.
