### ISSUE TITLE
Apache Beam has issues due to HBase's dependency on proto-lite

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#1272]
From a user: 

I think users (and in my case, the Apache Beam community) has been generally sloppy about these exclusions -- I'll give that a whirl.

* Apache Beam core need not depend on protobuf
* Apache Beam module A depends on something in HBase that exposes protobuf-lite
* Apache Beam module B depends on Bigtable which exposes protobuf-java

Randomly, they'll be used together and things will explode.

I guess based on the existence of module B we have to exclude protobuf-lite transitively everywhere in Apache Beam, and hope no one's generated protos against protobuf-lite.

(I think the HBase module just wanted ByteString).

**Comment by dhalperi** [comment]
I think this is likely not an issue with your client, but with a different Beam HBase library. Suggest closing and I'll respond if there's an issue here.

**Comment by sduskis** [comment]
Can you please point me toward the HBase library?  I wasn't aware that an HBase / CBT library was being built (that's what it looked like from your stacktrace offline)

**Comment by sduskis** [comment]
We spoke offline.  This isn't a CBT problem.
