### ISSUE TITLE
Dependency convergence issues with maven.

### ISSUE THREAD

**Issue by Slav4ik** [GoogleCloudPlatform/cloud-bigtable-client#1279]
consider dependency convergences in your repository.
Specifically, try using maven-enforcer-plugin or equivalent, before releasing a new build.

Last com.google.cloud.bigtable:bigtable-hbase-1.2:0.9.5.1 broke all our builds.
Namely: commons-cli, protobuf-java, httpcore and hadoop-common have dependency convergence issues

Thank you,
Slava

**Comment by igorbernstein** [comment]
Thanks for reporting. Can you clarify what broke in your build?

**Comment by igorbernstein2** [comment]
I don't think convergence is feasible here because our dependencies do not converge themselves and it would be a huge burden to maintain. Please see the discussion here:
https://github.com/grpc/grpc-java/issues/1421
