### ISSUE TITLE
Shading problem when using bigtable-hbase-1.2 and bigtable-hbase-dataflow v0.9.6

### ISSUE THREAD

**Issue by vc13819** [GoogleCloudPlatform/cloud-bigtable-client#1287]
If both bigtable-hbase-1.2 and bigtable-hbase-dataflow are dependencies in a project, we get the following error in runtime. Just having bigtable-hbase-1.2 works (actually while debugging, it worked with 0.9.6-SNAPSHOT..)

com.google.bigtable.v2.RowRange$Builder.setStartKeyClosed(Lcom/google/bigtable/repackaged/com/google/protobuf/ByteString;)Lcom/google/bigtable/v2/RowRange$Builder; at com.google.cloud.bigtable.hbase.BigtableExtendedScan.addRange(BigtableExtendedScan.java:74) at

**Comment by sduskis** [comment]
Yes.  The interaction is known issue, and we're going to look at this and
similar dependency problems over the next couple months and aiming for a
better experience for this situation. For now, I would suggest using only
bigtable-hbase-dataflow and not bigtable-hbase-1.2.
 bigtable-hbase-dataflow   contains all of the classes of bigtable-hbase-1.2
with some package relocation / shading.




Solomon Duskis |  Google Cloud Bigtable Tech Lead |  sduskis@google.com |
914-462-0531

**Comment by vc13819** [comment]
On Thu, Apr 13, 2017 at 6:17 PM, Solomon Duskis <notifications@github.com>
wrote:

> Yes. The interaction is known issue, and we're going to look at this and
> similar dependency problems over the next couple months and aiming for a
> better experience for this situation. For now, I would suggest using only
> bigtable-hbase-dataflow and not bigtable-hbase-1.2.
> bigtable-hbase-dataflow contains all of the classes of bigtable-hbase-1.2
> with some package relocation / shading.
>
no problem.

a tad bit wierd error...all our writes are failing...reads are fine.....

nothing in the logs:(
writes timeout at 3600 secs..which has got to be a default...
its embarrasing ...the amount of details or lack of it..but thats all  i
have
the new flex setup seems to be skimpy with logs:(

i have gotten rid of dataflow depedency.

**Comment by sduskis** [comment]
What environment are you using this in?  Are you using Dataflow?

**Comment by vc13819** [comment]
To debug this..I have deleted the dataflow functionality...its very
vanilla...all our writes are failing...no dataflow...no logs either:(

**Comment by sduskis** [comment]
Do you have any other jars on your classpath that start with bigtable-, specifically bigtable-protos?

**Comment by vc13819** [comment]
Just using bigtable-hbase-dataflow, does not get us BigtableExtendedScan.

**Comment by igorbernstein** [comment]
@vc13819 would you mind posting your dependencies?

**Comment by vc13819** [comment]
On Wed, Apr 19, 2017 at 9:35 AM, igorbernstein <notifications@github.com>
wrote:

> @vc13819 <https://github.com/vc13819> would you mind posting your
> dependencies?
>
    compile 'org.json:json:20151123'

  compile 'org.jsoup:jsoup:1.9.2'

  compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.24'

  compile group: 'io.netty', name: 'netty-tcnative-boringssl-static',
version: '1.1.33.Fork19'

  compile group: 'net.spy', name: 'spymemcached', version: '2.12.2'
  compile 'com.google.cloud.bigtable:bigtable-hbase-1.2:0.9.6.1'

compile 'com.google.cloud.bigtable:bigtable-hbase-dataflow:0.9.6.1'

  compile group: 'com.google.cloud.dataflow', name:
'google-cloud-dataflow-java-sdk-all',  version: '1.9.0'

  compile group: 'com.google.cloud', name: 'google-cloud-pubsub', version:
'0.13.0-alpha'

compile 'javax.validation:validation-api:1.0.0.GA'

  compile group: 'org.jgrapht', name: 'jgrapht-core', version: '0.9.2'

compile group: 'org.xerial.snappy', name: 'snappy-java', version: '1.1.1.3'

**Comment by sduskis** [comment]
We spoke offline a while back.  The original problem with went away after changing the dependencies.  There was a second problem regarding stuckness.  I'm going to close this issue for now.  If the stuckness is a problem, please open another bug.  If the dependency issue is still a problem, please let me know.
