### ISSUE TITLE
Pig regex doesn't work with CBT

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#1401]
A user is using pig, and setting a regex in [HBaseStorage](https://github.com/apache/pig/blob/trunk/src/org/apache/pig/backend/hadoop/hbase/HBaseStorage.java#L469):
```
        if (configuredOptions_.hasOption("regex")) {
            regex_ = Utils.slashisize(configuredOptions_.getOptionValue("regex"));
            addFilter(new RowFilter(CompareOp.EQUAL, new RegexStringComparator(regex_)));
        }
```
Hex values (\x01, \x02...) don't seem to work in this situation.

**Comment by garye** [comment]
Is it possible that this is against the emulator?
