### ISSUE TITLE
netty-tcnative conflict

### ISSUE THREAD

**Issue by jsw** [GoogleCloudPlatform/cloud-bigtable-client#1445]
I'm attempting to build a Scala project that integrates with both BigTable and Google Cloud Pubsub.

`google-cloud-pubsub:0.20.1-beta` depends on `netty-tcnative-boringssl-static:2.0.3.Final` (which contains `io.internal.tcnative.SSL`)

`bigtable-hbase-1.2:0.9.7.1` depends on `netty-tcnative-boringssl-static:1.1.33.Fork26` (which contains `org.apache.tomcat.jni.SSL`)

At runtime I will get an error such as 
```
i.n.h.s.OpenSsl:71 netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
```

Is there anyway I can make this work together?

**Comment by jsw** [comment]
To add more detail, it's the `OpenSsl` class that is looking to load different classes. The one in `bigtable-hbase-1.2-0.9.4` is looking for `org.apache.tomcat.jni.SSL` and the one in `netty-handler-4.1.11.Final` is looking for `io.netty.internal.tcnative.SSL`

**Comment by sduskis** [comment]
[Here](https://groups.google.com/forum/#!topic/google-cloud-bigtable-discuss/LvCdT4FGDl0) is the beginning of a discussion about this.  `netty-tcnative-boringssl-static:2.0.3.Final` has to be used with netty 4.1.9-Final.

Until the last release, you couldn't choose which version of netty you used, since we were including the netty packages in our bigtable-hbase jar, with a package rename.  Starting with the 1.0.0-pre1 release, we have an option that will allow you to set your own netty and then use netty-tcnative 2.0.

Use `bigtable-hbase-1.x:1.0.0-pre1` instead of `bigtable-hbase-1.2-0.9.7.1`.  You'd also have to explicitly set the following maven configuration to exclude default version of netty that bigtable-hbase depends on:

```
        <dependency>
            <groupId>com.google.cloud.bigtable</groupId>
            <artifactId>bigtable-hbase-1.x/artifactId>
            <version>1.0.0-pre1</version>
            <excludes>
                <exclude>
                    <groupId>io.netty</groupId>
                    <artifactId>*</groupId>
                <exclude>
            </excludes>
        </dependency>
```

**Comment by jsw** [comment]
@sduskis Do I then need to explicitly include the `netty-all` dependency? And can I instead include the individual netty dependencies? Otherwise, I will end up with duplication between `netty-all` and individual netty dependencies that are coming in via `google-cloud-pubsub`. And would would be the preferred version?

**Comment by sduskis** [comment]
I was hoping that by excluding the `bigtable-hbase` io.netty dependencies, that the `google-cloud-pubsub` io.netty dependencies would be effective for both `google-cloud-pubsub` use and bigtable-hbase-1.x use.

The main piece of advice from my end for now is using `bigtable-hbase-1.x:1.0.0-pre1` which will allow you more freedom in configuring your dependencies.  Hopefully you can get the right dependencies without too much tinkering.

I'll reach out to the grpc team and the authors of `google-cloud-pubsub` for more specific advice.

**Comment by jsw** [comment]
@sduskis I followed your suggestions. I'm using `bigtable-hbase-1.2:1.0.0-pre1`. My final classpath includes `netty-*:4.1.11.Final` as well as `netty-tcnative-boringssl-static:2.0.3.Final`. I still get a runtime error

```
2017-07-11 10:45:40,381 [DEBUG] [BigtableSession-startup-1] [] c.g.b.r.i.n.h.s.OpenSsl:71 netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
```

This appears to be happening because `bigtable-hbase-1.2-1.0.0-pre1.jar` contains the repackaged `com.google.bigtable.repackaged.io.netty.handler.ssl.OpenSsl.class` which is looking for `org.apache.tomcat.jni.SSL` in the classpath.

**Comment by sduskis** [comment]
The `-1.2` artifact won't work.  You need to use the `-1.x` artifact, with a literal 'x'

**Comment by jsw** [comment]
When I switch from `bigtable-hbase-1.2:0.9.4` to `bigtable-hbase-1.x:1.0.0-pre1` I get the following error
```
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error in chained row filter #1 : Error in interleaved row filter #0 : Error in field 'condition filter true case' : Error in field 'condition filter predicate' : Error in chained row filter #1 : Error in field 'value_range_filter' : Closed end_value must be non-empty
```

I'm updating an internal library and I'm not super familiar with BT and the client, and I didn't find anything relevant to the above error online. Let me know if I should take this question to another forum.

**Comment by sduskis** [comment]
I think that means that value is empty in the following line:

> `hasNoValidLeaseFilter.addFilter(new SingleColumnValueFilter(columnFamily, column, CompareFilter.CompareOp.LESS, value))`

`< {empty array}` doesn't seem like a valid test.

**Comment by jsw** [comment]
`value` is never empty. I added logging to verify. It worked correctly with the above code and previous client library. It's the first filter that it doesn't like

```new SingleColumnValueFilter(columnFamily, column, CompareFilter.CompareOp.EQUAL, Array[Byte]())```

The intent is to find rows where the column is empty/null (filter #1) or where the value is less than `value` (filter #2). It used to work, but seems like the newer library doesn't like comparing to an empty byte array. Is there a better way to achieve the same effect?

**Comment by sduskis** [comment]
Thanks for the clarification.  I got lost in the details.  We used to use a slightly different version of the Equals comparator, but that was changed due to issue #1264.  I'll put in a special case for the empty byte[] value.

**Comment by jsw** [comment]
Thanks, and let me know if there's a better way to check for empty/null column value.

**Comment by jsw** [comment]
Will this change be included in the `1.0.0-pre2` release?

**Comment by sduskis** [comment]
Yes, the change will be in -pre2.  FWIW, I think that for now, you can use this instead:

`new SingleColumnValueFilter(columnFamily, column, CompareFilter.CompareOp.EQUAL, new RegexStringComparator(Array[Byte]()))`

**Comment by anhldbk** [comment]
@jsw : You can resolve this issue by marking following dependencies to be loaded first:

```xml
   <dependencies>
        <!-- https://mvnrepository.com/artifact/io.netty/netty-all -->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.16.Final</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.netty/netty-tcnative-boringssl-static -->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.7.Final</version>
        </dependency>

   </dependencies>
```

**Comment by igorbernstein** [comment]
One better:

You can use bigtable-hbase-1.x-shaded 1.0.0, it includes a private copy of tcnative and uses hbase-shaded-client, which minimize the surface area for dependency conflicts
