### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor

### ISSUE THREAD

**Issue by wwchen** [GoogleCloudPlatform/cloud-bigtable-client#1457]
I switched my project from
```
"com.google.cloud.bigtable" % "bigtable-hbase-1.2" % "0.9.6.2"
```
to
```
"com.google.cloud.bigtable" % "bigtable-hbase-1.x" % "1.0.0-pre1"
```
and now I'm getting this error. Any thoughts?

```
[info] Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
[info] 	at io.grpc.internal.ClientCallImpl.<init>(ClientCallImpl.java:104)
[info] 	at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:554)
[info] 	at com.google.cloud.bigtable.grpc.async.ThrottlingClientInterceptor.interceptCall(ThrottlingClientInterceptor.java:50)
[info] 	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:119)
[info] 	at com.google.cloud.bigtable.grpc.io.GoogleCloudResourcePrefixInterceptor.interceptCall(GoogleCloudResourcePrefixInterceptor.java:58)
[info] 	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:119)
[info] 	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.interceptCall(RefreshingOAuth2CredentialsInterceptor.java:188)
[info] 	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:119)
[info] 	at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:533)
[info] 	at com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel.newCall(ChannelPool.java:162)
[info] 	at com.google.cloud.bigtable.grpc.io.ChannelPool.newCall(ChannelPool.java:282)
[info] 	at com.google.cloud.bigtable.grpc.async.BigtableAsyncUtilities$Default$1.startNewCall(BigtableAsyncUtilities.java:80)
[info] 	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.run(AbstractRetryingOperation.java:238)
[info] 	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.getAsyncResult(AbstractRetryingOperation.java:260)
[info] 	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.getBlockingResult(AbstractRetryingOperation.java:273)
[info] 	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.mutateRow(BigtableDataGrpcClient.java:235)
[info] 	at com.google.cloud.bigtable.hbase.BigtableTable.put(BigtableTable.java:331)
[info] 	... 34 more
```

**Comment by sduskis** [comment]
`com.google.common.util.concurrent.MoreExecutors` comes from the guava project.  HBase has very old dependencies, including an old version of guava.  If you have any hbase artifacts in your pom, please remove them, and then things should work.  If you're using hadoop or spark, please use the `bigtable-hbase-1.x-hadoop` artifactId instead of `bigtable-hbase-1.x`.

**Comment by wwchen** [comment]
The dependenices I have are:
```
  "io.netty" % "netty-tcnative-boringssl-static" % "1.1.33.Fork26",
  "com.google.cloud.bigtable" % "bigtable-hbase-1.x" % "1.0.0-pre1",
  "com.readytalk" % "metrics3-statsd" % "4.2.0",
  "com.github.davidb" % "metrics-influxdb" % "0.9.3"
```

I ran dependency check, and the only one with `org.apache.hbase:hbase-shaded-client:1.3.1` is `com.google.cloud.bigtable:bigtable-hbase-1.x:1.0.0-pre1`

**Comment by wwchen** [comment]
Oh, unless you mean guava? Ok, there's `com.google.guava:guava-jdk5:17.0` used in  `com.google.apis:google-api-services-bigquery:v2-rev248-1.21.0`

Let me check here..

**Comment by igorbernstein2** [comment]
Would it be possible to paste the output of `gradle dependencies` here?

**Comment by wwchen** [comment]
Ok, so good news is, I might've found the culprit, which is the `guava-jdk5:17.0`. Removing the bigquery project worked. 

Bad news is, even the [latest bigquery Java](https://mvnrepository.com/artifact/com.google.apis/google-api-services-bigquery/v2-rev350-1.22.0) API has a dependency to [com.google.guava:guava-jdk5:17.0](https://mvnrepository.com/artifact/com.google.guava/guava-jdk5/17.0/usages)

Good news is, I can simply exclude `guava-jdk5` from the jar :)

**Comment by sduskis** [comment]
I think that google-api-services-bigquery might be deprecated in favor of google-cloud-bigquery

**Comment by wwchen** [comment]
While true, this statement has a 70% chance of frustrating the future me :)
```This is a Beta release of the Cloud Client Libraries for the Google BigQuery API. These libraries might be changed in backward-incompatible ways and are not subject to any SLA or deprecation policy.
```

[source](https://cloud.google.com/bigquery/docs/reference/libraries) and [this](https://developers.google.com/api-client-library/java/apis/bigquery/v2)
