### ISSUE TITLE
checkAndPut returns unexpected false

### ISSUE THREAD

**Issue by helin24** [GoogleCloudPlatform/cloud-bigtable-client#1469]
We recently upgraded from `bigtable-hbase-1.2:0.9.6.2` to `bigtable-hbase-1.x:1.0.0-pre1` and we are seeing some issues with the `Table::checkAndPut` atomic function. This was tested against a bigtable emulator and also against a real cluster.

```
table.put(new Put("rowKey2".getBytes()).addColumn("cf1".getBytes(), "column1".getBytes(), bb.array()));

ByteBuffer bb2 = ByteBuffer.allocate(4);
bb2.putInt(15);

boolean result = table.checkAndPut("rowKey2".getBytes(), "cf1".getBytes(), "column1".getBytes(),
    CompareFilter.CompareOp.LESS, bb2.array(),
    new Put("rowKey2".getBytes()).addColumn("cf1".getBytes(), "column1".getBytes(), bb2.array()));
assertTrue(result); // result is false
```

**Comment by sduskis** [comment]
Issue #1348 described some inconsistencies between the HBase implementation and the Cloud Bigtable implementation of checkAnd* diverged.  <=, <, >, and >= are all inverted.  You'll have to change LESS to GREATER.

**Comment by helin24** [comment]
Ah! Thank you.
