### ISSUE TITLE
Consider publishing a shaded version of bigtable-client-core.

### ISSUE THREAD

**Issue by steveniemitz** [GoogleCloudPlatform/cloud-bigtable-client#1500]
Now that [netty can be shaded](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/1487/) it would be great to have a version of bigtable-client-core that is fully shaded, much like bigtable-hbase-1.x-shaded.

I'd be happy to submit a PR if this is something other people would use too.

**Comment by sduskis** [comment]
Can you please provide more context to this?  What are you trying to accomplish?

**Comment by steveniemitz** [comment]
We currently use netty elsewhere in our codebase (finagle specifically).  By also including bigtable-client-core (gRPC + netty transitively) we introduce a very real possibility of conflicting versions.

So far we've been lucky that the versions align enough to not cause catastrophic runtime failures, but there's no guarantee.  I'll most likely be producing my own shaded artifact for bigtable-client-core internally now that it is shadable, but it seems like something other people would also find useful.

**Comment by sduskis** [comment]
Most of our users use the HBase layer, where this is a solved problem, although we'll have to figure this out for Beam.  You chose a less used approach.  We can support you, but I think that we'll hold off on a general shaded bigtable-client-core until there's at least one more user who needs it.

You can exclude our versions of io.netty and netty-tcnative in favor of your own versions.  gRPC and netty ought to be backwards compatible; we used newer versions of gRPC with older netty versions.  You can also shade bigtable-client-core.

We'll also touch base with other GCP teams about this problem to get to the right solution.

**Comment by steveniemitz** [comment]
Understood, it's not a big deal for me to publish a shaded version internally.  I have run into issues w/ gRPC + netty differences but I think that was mostly pre-tcnative 2.0.

Beam is also a use-case for me, but running the bundled version of bigtable-client-core is good enough for now (although a slightly patched version...).

You can close this if you want!

**Comment by mbrukman** [comment]
@steveniemitz — when you say:

> Beam is also a use-case for me, but running the bundled version of bigtable-client-core is good enough for now (although a slightly patched version...).

Can you share what specifically you needed to patch? Anything we should fix in the common version?

**Comment by steveniemitz** [comment]
@mbrukman I was just referring to https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/1498 :)

**Comment by mbrukman** [comment]
@steveniemitz – got it, thanks!

**Comment by steveniemitz** [comment]
Something odd I just noticed when setting up my shaded build.  I copied the netty part from bigtable-hbase-1.x-shaded, which relocates the netty native resources like this:
```
                <relocation>
                  <pattern>META-INF/native/libnetty</pattern>
                  <shadedPattern>META-INF/native/libcom-google-bigtable-repackaged-netty</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>META-INF/native/netty</pattern>
                  <shadedPattern>META-INFO/native/com-google-bigtable-repackaged-netty</shadedPattern>
                </relocation>
```

note the dashes in com-google-bigtable.

When I tried this I ran into the oh-too-common "Jetty ALPN/NPN has not been properly configured" error.  Stepping through the load process I noticed it was looking for `com_google_bigtable_repackaged_netty` (note the underscores instead).  I changed my shading pattern to match and got everything to work.

The only difference between the two is that I upgraded to netty 4.1.15 in my build.  Has the hbase one been tested?  Or did the expected file pattern change between 4.1.14 and 4.1.15?

**Comment by steveniemitz** [comment]
I should have assumed netty would be making random backwards incompatible changes :P

**Comment by sduskis** [comment]
We now use grpc-netty-shaded (like other GCP clients), which hopefully should fix the non-Beam case.  Beam was updated to use the latest and greatest version of all clients and grpc, so I think that case is solved as well.

**Comment by steveniemitz** [comment]
wow blast from the past!  Things have been much better now that the netty/tcnative interfaces have stabilized.  In fact now we share the same netty ELG/worker pool between both gRPC and finagle in our service, which has shown some significant performance benefits.

**Comment by sduskis** [comment]
OK.  It sounds like things are working out.  I'm going to close this issue.  Please reopen if there's something new to consider.
