### ISSUE TITLE
Is scan.setReversed(true) supported? 

### ISSUE THREAD

**Issue by yaojuncn** [GoogleCloudPlatform/cloud-bigtable-client#1512]
Hi, Google, 

version: com.google.cloud.bigtable:bigtable-hbase-1.x-hadoop:1.0.0-pre3

when I try to set reversed during Scan using "scan.setReversed(true)", 
it is still returning result in the lexicographically order. 

then I tried to switch startrow/endrow, that is making starting row > end row, 
I got following result:
INVALID_ARGUMENT: Error in field 'row_ranges' : Error in element #0 : start_key must be less than end_key

is the setReversed(true) supported? 

Thanks

**Comment by sduskis** [comment]
Bigtable does not support reverse scanning.

**Comment by yaojuncn** [comment]
thanks, is there a list of non-supported features of the HBase API of BigTable client? 
without knowing this (or testing this), it might be hard/risky for us to code based on the Hbase API?

**Comment by sduskis** [comment]
The documentation is [here](https://cloud.google.com/bigtable/docs/hbase-differences).

**Comment by yaojuncn** [comment]
thanks!
