### ISSUE TITLE
is SingleColumnValueFilter.setFilterIfMissing supported in BigTable?

### ISSUE THREAD

**Issue by yaojuncn** [GoogleCloudPlatform/cloud-bigtable-client#1533]
Hi, Google, 

I read https://cloud.google.com/bigtable/docs/hbase-differences and did not find any comments about SingleColumnValueFilter.setFilterIfMissing ,

however, during my test, I have one record with a column  not set, 

                SingleColumnValueFilter jobIdFilter = new SingleColumnValueFilter(column_family, column_name, CompareFilter.CompareOp.EQUAL, Bytes.toBytes("-1"));
                jobIdFilter.setFilterIfMissing(false);

that row is not returned by the scan, 

am I doing something wrong or setFilterIfMissing() is no supported in BigTable?

Thanks
Jun

**Comment by sduskis** [comment]
I think you're looking for `setFilterIfMissing(true)`.  The default is false, meaning don't return the row if the qualifier is missing.

**Comment by yaojuncn** [comment]
thanks, actually using false is right. but my case is that the values were set to ""  that break this.
