### ISSUE TITLE
Cells limited when scanning table with ColumnPaginationFilter

### ISSUE THREAD

**Issue by sweetca** [GoogleCloudPlatform/cloud-bigtable-client#1539]
From doc https://cloud.google.com/bigtable/docs/hbase-differences
we have info that when we scanning with ColumnPaginationFilter we limited to only one column family.
I'm trying to scan my table by ONE column family and this family has more than 20 cells.
The problem that I cause:  when iterate Row - I'm limited to 10 first column.
Here is how I set up scan
```
        Scan scan = new Scan();
        scan.addFamily(CF_STATIC);

        FilterList scanFilters = new FilterList(FilterList.Operator.MUST_PASS_ALL);

        if (search.isSized()) {
            scanFilters.addFilter(new SingleColumnValueFilter(
                    CF_STATIC,
                    COLUMN_DISK_USAGE,
                    CompareFilter.CompareOp.GREATER_OR_EQUAL,
                    Bytes.toBytes(search.getSize())
            ));
        }

        scanFilters.addFilter(new SingleColumnValueFilter(
                CF_STATIC,
                COLUMN_ACTIVE,
                CompareFilter.CompareOp.EQUAL,
                Bytes.toBytes(true)
        ));

        if (search.isLimited()) {
            int offset = search.hasOffset() ? search.getSearchOffset() : 0;
            scanFilters.addFilter(new ColumnPaginationFilter(search.getSearchLimit(), offset));
        }

        scan.setFilter(scanFilters);
        return scan;
```
My `com.google.cloud.bigtable` version is *1.0.0*, also I had a shot on *1.0.0-pre3* with same behavior. 

Do we have any possibility to scan 20 cells in a single column family?
For me, it looks like a bug at least in public documentation.
@sduskis Solomon, can you put some light here, please?

**Comment by sduskis** [comment]
It looks like we limit the number of cells per row.  Here's the code that maps HBase to Cloud Bigtable:

`RowFilter.newBuilder() .setCellsPerRowLimitFilter(filter.getLimit())`

[Here](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/filters/ColumnPaginationFilterAdapter.java)'s the full class.

This could very well be a difference between our client and HBase, which is not documented correctly.

**Comment by sweetca** [comment]
@sduskis 
Solomon, thanks a lot for the response.
My point of view: this is quite unexpected behavior. 
Is it possible to upgrade code source of ColumnPaginationFilterAdapter with additional *CellsLimit* param support?
I'm pretty sure that a lot of guys who have much more columns than me cause some troubles here...

It's like you want to search for 1_000 objects but you have 10_000 columns and you will have no choice to search less than 10_000 objects if you want to get all your columns in result.

A second point here: you do not expect such setting inside of *ColumnPaginationFilter* behavior.

@sduskis 
Solomon, are you agree with it?

**Comment by sduskis** [comment]
@sweetca, I'm having a bit of trouble understanding what you're aiming for here.  `ColumnPaginationFilter` already takes a cell limit and an offset.

Are you looking to get a cells limit per qualifier parameter?  If so, we may need to create a new type of filter that's different than `ColumnPaginationFilter`.

**Comment by sweetca** [comment]
@sduskis 
Thanks.
