### ISSUE TITLE
Bigtable hbase client memory leak

### ISSUE THREAD

**Issue by kaviarasugovindarajusc** [GoogleCloudPlatform/cloud-bigtable-client#1540]
BigTable client: com.google.cloud.bigtable:bigtable-hbase-1.x-hadoop:1.0.0-pre3
Runtime: dataproc

We already filed an issue regarding this with pre1 version here: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/1470. Same issue is still happening with the new version and the process goes out of memory sooner if we do Bigtable IO more frequently.

**Comment by sduskis** [comment]
The problem in #1470 related to situations where scans were not closed.  Can you please give more details about what you're doing in dataproc?  What's the relation to BigtableIO?

**Comment by kaviarasugovindarajusc** [comment]
@sduskis - What do you mean by "scans were not closed"?

This is what exactly we do in dataproc:
1) We do a scan using a prefix and a pageFilter set to a small number like 10.
2) For each row scanned, update the row
[ Some dataproc in memory processing and no Bigtable IO here]
3) Create some new rows. Row count could be from 1000 to 2000.

**Comment by igorbernstein2** [comment]
The issue in #1470 was caused by scans not being fully consumed. So if the result set for a scan was supposed to contain 100 rows, but the user only called Scanner.next() once, that would indefinitely block a grpc thread.

The issue you are describing here, seems to be different. Would it be possible for you to provide sample code demonstrating the leak? Also, can you clarify what you mean by memory leak? does the pipeline crash with out of memory exception? if so, at what Xmx does it OOM?

**Comment by sduskis** [comment]
If this is an OOM, you'd have to take a heap dump and do some analysis to see what's consuming memory.  Once you have that, we may be able to help.

Some pro tips in the mean time...

1) use BufferedMutator for your writes.
2) See here for good settings for batch operations: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableConfiguration.java#L163

**Comment by kaviarasugovindarajusc** [comment]
@sduskis @igorbernstein2 - Even before the process runs out of memory, the Spark driver kills the app by sending SIGTERM signal and we dont have a heap dump when the job died. I took a heap dump when the job was running for sometime. It showed 100s of grpc threads each showing 10-15MB. It is more of a thread leak. Our Xmx is 4g btw.

**Comment by kaviarasugovindarajusc** [comment]
@sduskis - Thanks for the pro tips!

**Comment by kaviarasugovindarajusc** [comment]
@igorbernstein2 - This is our scan code

`                    try(ResultScanner resultScanner = table.getScanner(scan)) {
                        Result result = resultScanner.next();
                        while (null != result) {
                            byte[] resultBytes = result.getValue(CF_DEFAULT, COL_BATCHPULL_BATCH_ID.getColumnVal());
                            String batchId = Bytes.toString(resultBytes);
                            batchIdList.add(batchId);
                            result = resultScanner.next();
                        }
                    }
`

**Comment by sduskis** [comment]
What does your `scan` configuration look like?

**Comment by kaviarasugovindarajusc** [comment]
@sduskis - This is my Scan config:

```
Scan scan = new Scan();
scan.setStartRow(Bytes.toBytes(batchPullStatusRowKeyStart));

FilterList filterList = new FilterList();
filterList.addFilter(new PrefixFilter(..));
filterList.addFilter(new SingleColumnValueFilter(..));
filterList.addFilter(new PageFilter(..));
scan.setFilter(filterList);
```

**Comment by sduskis** [comment]
The scan seems right.  Hopefully some of the other settings can help.

**Comment by kaviarasugovindarajusc** [comment]
@sduskis - This is our bigtable connection setting

```
    private Connection buildBigtableConnection() throws IOException {
        this.conf = HBaseConfiguration.create();
        this.conf.setClass("hbase.client.connection.impl", BigtableConnection.class, Connection.class);
        this.conf.set("google.bigtable.project.id", this.projectId);
        this.conf.set("google.bigtable.instance.id", this.instanceId);
        if (null != this.timeoutMs) {
            this.conf.set("google.bigtable.grpc.retry.enable", "" + this.retriesEnabled);
            this.conf.set("google.bigtable.rpc.use.timeouts", "true");
            this.conf.set("google.bigtable.rpc.timeout.ms", "" + this.timeoutMs);
            this.conf.set("google.bigtable.long.rpc.timeout.ms", "" + this.timeoutMs);
            this.conf.set("google.bigtable.grpc.retry.max.elapsed.backoff.ms", "" + this.maxRetryBackOffMs);
        }

        return ConnectionFactory.createConnection(this.conf);
    }
```

**Comment by sduskis** [comment]
Please add this: 
`this.conf.set(BigtableOptionsFactory.BIGTABLE_USE_CACHED_DATA_CHANNEL_POOL, "true");`

**Comment by kaviarasugovindarajusc** [comment]
@sduskis - I'll add this. Will it fix the problem? If not, do you need any other info from me?

**Comment by sduskis** [comment]
It's unclear what the problem actually is, without having a deeper understanding of your use case.

My suggestion will reduce the number of open connections, which may help the problem you're seeing.  

I would suggest opening up a support request through the cloud console, since anything we do via github is educated guesswork without specific data.

**Comment by kaviarasugovindarajusc** [comment]
@sduskis - Sounds good! I'll create a case right now.

**Comment by sduskis** [comment]
@kaviarasugovindarajusc, did you have any luck?

**Comment by kaviarasugovindarajusc** [comment]
@sduskis - Looks like the issue has gone away with the cached data channel pool setting. We are yet to confirm but it hasn't happened in the last 10days.

**Comment by sduskis** [comment]
That's awesome!

I'll create a separate issue to have cached data channels turned on by default.
