### ISSUE TITLE
Turn on cached channel pooling by default

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#1561]
Cloud Bigtable should have `BigtableOptions.useCachedDataPool = true` by default.

See #1540

**Comment by sduskis** [comment]
I'm going to close this, since we're going to transition to google-cloud-java, and it won't have cached data pool.  @igorbernstein2, it's something to think about.

**Comment by igorbernstein2** [comment]
I would like to pull this out of the client and push it into our beam connector
