### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.beam.runners.dataflow.options.DataflowWorkerHarnessOptions.getDataflowClient()Lcom/google/api/services/dataflow/Dataflow

### ISSUE THREAD

**Issue by Money-Honey** [GoogleCloudPlatform/cloud-bigtable-client#1585]
There is issue with running dataflow job. I'm using pipelines and custom 
Issue looks like:
`java.lang.NoSuchMethodError: org.apache.beam.runners.dataflow.options.DataflowWorkerHarnessOptions.getDataflowClient()Lcom/google/api/services/dataflow/Dataflow;
at com.google.cloud.dataflow.worker.DataflowWorkUnitClient.<init> (DataflowWorkUnitClient.java:73)
at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness.run (DataflowBatchWorkerHarness.java:70)
at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness.main (DataflowBatchWorkerHarness.java:58)`

Pipeline looks like:

`
public interface SomeOptions extends GcpOptions {
...
}

Pipeline pipeline = Pipeline.create(options);
pipeline
                .apply("Read table", Read.from(CloudBigtableIO.read(config)))
                .apply("Map", MapElements.via(new MapFunction()))
                .apply("foreach", Count.globally());`

Dependencies look like:
`    compile "com.google.apis:google-api-services-dataflow:v1b3-rev221-$googleApiVersion"

     compile("com.google.http-client:google-http-client:$googleApiVersion") {
        exclude group: 'com.google.guava'
        force = true
    }

    compile("com.google.api-client:google-api-client:$googleApiVersion") {
        exclude group: 'com.google.guava'
        force = true
    }
    compile "com.google.cloud.bigtable:bigtable-beam-import:1.0.0-pre4"
    compile('com.google.cloud:google-cloud-storage:1.14.0') {
        exclude(module: "google-api-client")
        exclude group: 'com.google.guava'
    }
    compile("com.google.apis:google-api-services-storage:v1-rev116-$googleApiVersion") {
        exclude(module: "google-api-client")
        exclude group: 'com.google.guava'
    }

    compile('com.google.guava:guava:20.0') {
        force = true
    }

    compile ("com.google.cloud:google-cloud:0.26.0-alpha") {
        exclude group: 'com.google.guava'
    }
`
Where googleApiVersion = 1.22.0

Job is packed in using shadowJar
`shadowJar {

    doFirst {
        zip64 true
        configurations = [project.configurations.compile]
        mergeServiceFiles()
    }
}`

Have no idea why it's happened because `at com.google.cloud.dataflow.worker.DataflowWorkUnitClient` is on server side and there is oppotunity check sources

**Comment by igorbernstein2** [comment]
Hi,
bigtable-beam-import is meant to be a standalone command line utility that allows users to import and export hbase sequence files to/from Cloud BIgtable. It wasn't meant to be used as a library, it's only been tested as a command line utility.

What are you trying to accomplish? The example code you've provided seems unrelated to sequence files. If you are simply trying to access Cloud Bigtable from dataflow, please use bigtable-hbase-beam. If you are trying to custom the import/export process, please provide further details.

Thanks

**Comment by sduskis** [comment]
I would suggest upgrading to `com.google.cloud.bigtable:bigtable-beam-import:1.0.0` rather than `com.google.cloud.bigtable:bigtable-beam-import:1.0.0-pre4` as a starting point.  -pre4 had a package renaming problem.

**Comment by Money-Honey** [comment]
Hi guys. Thanks a lot for answering!!!
Generally i have fixed issue. More details there were in stackdriver output. I had just hadn't idea where i can to read more details about issue. In particular the problem was related to incorrect manipulations with dependencies like, protobuf and guava. Hence i have just applied some shadow transformations to specific modules and solved issue.

Btw, I agree that `bigtable-beam-import` it's not the best way to pull all needed dependencies to work with dataflow, beam, and hbase, but it was done for investigation, currently i'm using this one `com.google.cloud.bigtable:bigtable-beam` and others.
