### ISSUE TITLE
Snapshot cluster needs a configuration option

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#1590]
There needs to be a way for multi-cluster instances to use the snapshot functionality with the java hbase client.

**Comment by igorbernstein2** [comment]
Can you clarify? I think it's covered by:
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/1580/files#diff-16810051a0030a7f4f1590d7dff99013R76

**Comment by kevinsi4508** [comment]
@igorbernstein2, we need an instance with multiple clusters in it.
This is not quite yet supported, I have manually tested it. This needs a project that has both Replication and Snapshot enabled.

**Comment by sduskis** [comment]
Thanks @igorbernstein2.  I missed that configuration.
