### ISSUE TITLE
whenever I use bigtable-beam-import-1.0.0-shaded.jar export I have to do a ^C to have it move onto the next command

### ISSUE THREAD

**Issue by ilocruz** [GoogleCloudPlatform/cloud-bigtable-client#1615]
[BigTable_ExportExcerpt.txt](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/files/1647032/BigTable_ExportExcerpt.txt)
I'm trying to use bigtable-beam-import-1.0.0-shaded.jar export to backup my BigTable Files.
It does work, but after every command I have to issue a ^C to make it go on to the next java -jar command. And what is weird it doesn't do this when I do an import.
I found a solution its to use bigtable-beam-import-1.0.0-pre4-shaded.jar instead that I got via THE MAVEN REPO.
Here is how I am using it ( like the book says ) and even if I just issue the command from the command line it still does the same.

**Comment by ilocruz** [comment]
Here is how it looks too:
[7:25 AM]
2018-01-11 15:24:54 INFO  DataflowPipelineJob:334 - Job 2018-01-11_07_22_03-16317998385704855024 finished with status DONE.
2018-01-11 15:24:54 INFO  ExportJob:154 - Job finished with state: DONE
[7:25 AM]
and it will sit here forever in my script never going forward until I put in a ^C
[7:26 AM]
^C
2018-01-11 15:26:28 INFO  DataflowRunner:243 - PipelineOptions.filesToStage was not specified. Defaulting to files from the classpath: will stage 1 files. Enable logging at DEBUG level to see which files will be staged.
2018-01-11 15:26:29 INFO  DataflowRunner:533 - Executing pipeline on the Dataflow Service, which will have billing implications related to Google Compute Engine usage and other Google Cloud Services.
2018-01-11 15:26:29 INFO  PackageUtil:275 - Uploading 1 files from PipelineOptions.filesToStage to staging location to prepare for execution.
[7:26 AM]
then it starts again

**Comment by igorbernstein2** [comment]
I'm guessing there is a runaway thread that's preventing the driver from shutting down cleanly. I'll try to look at this today. It would be immensely helpful if you could provide a thread dump of the process after it prints "Job finished with state: DONE"

```shell
# get the pid of the process
jps -l

jstack -l PID_FROM_JPS
```

Thanks!

**Comment by sduskis** [comment]
We can probably call `System.exit(0)` explicitly at the end of the pipeline.

**Comment by ilocruz** [comment]
I meant:
 jstack -l 9753 > jstack.txt

**Comment by igorbernstein2** [comment]
@ilocruz thank you, that is extremely helpful. We have a lead as to what could be causing the hang. We will be in touch shortly with a fix

**Comment by igorbernstein2** [comment]
Hi @ilocruz, it seems like this issue was introduced by one of our dependencies. It has since been fixed, so the next version of bigtable-beam-import will no longer hang. If you don't want to wait for the next release, you can build a local version:

```shell
 git clone https://github.com/GoogleCloudPlatform/cloud-bigtable-client.git
cd cloud-bigtable-client

# checkout the revision that updated dependencies
git checkout 0cbb8d2057be94ab73408a5718d160aeed4cdf2a

mvn clean package

java -jar \
  bigtable-dataflow-parent/bigtable-beam-import/target/bigtable-beam-import-1.0.1-SNAPSHOT-shaded.jar \
  export ....
```

I apologize for the inconvience

**Comment by sduskis** [comment]
@ilocruz, we're going to make a new build early next week (probably 1.1.0).  We testing the change ourselves, but it would indeed be awesome if you could test the changes as well.  Here is a [link to a built snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/google/cloud/bigtable/bigtable-beam-import/1.0.1-SNAPSHOT/bigtable-beam-import-1.0.1-20180126.142423-8-shaded.jar)

**Comment by ilocruz** [comment]
sure I will test it right now and get back to you in a few.
-ilo

**Comment by ilocruz** [comment]
Igor That one works GREAT - It doesn't stop after DONE when in a script -
Thanks


2018-01-31 17:36:51 INFO  DataflowPipelineJob:334 - Job
2018-01-31_09_33_53-12242129239590210601 finished with stat
us DONE.
2018-01-31 17:36:51 INFO  ExportJob:154 - Job finished with state:
DONE
2018-01-31 17:36:54 INFO  DataflowRunner:243 -
PipelineOptions.filesToStage was not specified. Defaulting to files
from the classpath: will stage 1 files. Enable logging at DEBUG level
to see which files will be staged.
2018-01-31 17:36:55 INFO  DataflowRunner:533 - Executing pipeline on
the Dataflow Service, which will

And I did a import into BigTable too it all checks out good.


Thanks

-ilo

**Comment by igorbernstein2** [comment]
Glad to be of help. Sorry for the inconvenience.
