### ISSUE TITLE
Unable to export Bigtable table using bigtable-beam-import

### ISSUE THREAD

**Issue by rlucioni** [GoogleCloudPlatform/cloud-bigtable-client#1616]
I'm trying to use bigtable-beam-import (`bigtable-beam-import-1.0.0-shaded.jar`) to export Bigtable sequence files to GCS. I'm running the export command as instructed [here](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/tree/master/bigtable-dataflow-parent/bigtable-beam-import) and [here](https://cloud.google.com/bigtable/docs/exporting-sequence-files#bigtable) to export several tables of different sizes. The resulting Dataflow jobs succeed when run against tables on the order of tens of GB in size. However, Dataflow jobs run against tables on the order of tens of TB in size fail with four instances of the following message after running for several hours:

```
(1779ae0c104c4266): java.io.IOException: Failed to advance reader of source: Split start: 'foo/bar|2-57912', end: 'foo/bar|2-57c5', size: 5637144576.
	at com.google.cloud.dataflow.worker.WorkerCustomSources$BoundedReaderIterator.advance(WorkerCustomSources.java:592)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation$SynchronizedReaderIterator.advance(ReadOperation.java:385)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:183)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:148)
	...
```

Instances of the above message are followed by:

```
(b338ffd0a36e15ee): Workflow failed. Causes: (9422aa7a760b7f3a): S01:Read table+Format results/Map+Write/Window.Into()/Window.Assign+Write/WriteUnwindowedBundles+Write/View.AsIterable/View.CreatePCollectionView/ParDo(ToIsmRecordForGlobalWindow) failed., (4b73697872419ac9): A work item was attempted 4 times without success. Each time the worker eventually lost contact with the service. The work item was attempted on: 
  exportjob-rlucioni-011822-01181421-0349-harness-08gm,
  exportjob-rlucioni-011822-01181421-0349-harness-53fs,
  exportjob-rlucioni-011822-01181421-0349-harness-53fs,
  exportjob-rlucioni-011822-01181421-0349-harness-53fs
```

The split start and end are not consistent across failures, nor is the amount of time the job runs before failing.

I've followed the advice in the [pipeline troubleshooting](https://cloud.google.com/dataflow/pipelines/troubleshooting-your-pipeline) guide to no avail. I'd appreciate any help or advice here. Please let me know if I can provide any more information.

**Comment by sduskis** [comment]
This isn't enough for us to go on.  Would you be able to open up a support ticket for this problem?  There isn't enough for us to go on in your description of the problem.  This might be a Cloud Bigtable issue or a Dataflow issue.  We would need more PII type information like project id and job id in order to further diagnose the root cause.

**Comment by rlucioni** [comment]
Yes, I can open a support ticket for this. I opened this just in case it was it was something with bigtable-beam-import that I wasn't seeing. Thank you for responding so quickly.

**Comment by KJTsanaktsidis** [comment]
I'd be really interested in whether or not you got this resolved. We have a large dataset and I need to find a way to make backups. How large is your dataset/how long does the export end up taking?

**Comment by rlucioni** [comment]
@KJTsanaktsidis it turned out to be a problem reading some very large rows. They were large because they had many versions that hadn't been garbage collected. We only needed the most recent version in our backup. Running the import jar with `--bigtableMaxVersions=1` fixed the problem for us.
