### ISSUE TITLE
Provide shutdown hook in BulkMutation

### ISSUE THREAD

**Issue by nezdolik** [GoogleCloudPlatform/cloud-bigtable-client#1666]

**Comment by sduskis** [comment]
Can you please give more information about what you're looking for?

**Comment by nezdolik** [comment]
BulkMutation has internal ExecutorService, in case client code wants to perform shutdown, it's currently not possible to perform clean shutdown for BulkMutation and await termination of that ExecutorService.

**Comment by sduskis** [comment]
The [`BulkMutation.flush()`](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/BulkMutation.java#L442) method is intended as a method of a clean shutdown of BulkMutation.  Use `flush()` to await the completion of all requests sent to the BulkMutation, or wait on all `Future`s returned by `add()`.

The Executor passed should have a daemon threadpool, and should be managed externally to `BulkMutation`.
