### ISSUE TITLE
CheckAndMutate methods should not set client-side timestamps

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#1709]
If a user doesn't set timestamps, `Put` operations get client-side timestamps.  That's done some that retries can kick in and not write multiple cells of the same value.  That works great for regular put and BufferedMutator calls, but seems to cause some interesting race conditions for `checkAndPut` in some cases.

checkAndPut should use a `PutAdapter` that doesn't set client-side timestamps for the default case.

**Comment by igorbernstein2** [comment]
Also, we should add some docs explaining that user provided timestamps should be used when strict CAS behavior is required. Pushing the timestamp generation only minimizes the race condition, but doesn't prevent it: 2 frontends can still send 2 mutations downstream that will arrive to backends out of order

**Comment by sduskis** [comment]
This was fixed with #1719.
