### ISSUE TITLE
tcnative libraries are not correctly shaded in Windows environments (META-INF)

### ISSUE THREAD

**Issue by norbjd** [GoogleCloudPlatform/cloud-bigtable-client#1713]
Hello,

When instanciating a `BigtableConnection` using `bigtable-hbase-1.x-hadoop` dependency on Windows, an exception is thrown : 

`java.lang.IllegalArgumentException: ALPN is not configured properly. See https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting for more information.`

The weird thing is that it works on Linux and Mac OS. So we investigate and found that this error happens because in `OpenSsl` class (shaded), we have an `UNAVAILABILITY_CAUSE` equal to `failed to load any of the given library : [netty-tcnative-windows-x86_64, ...]`.

Indeed, the Windows tcnative library is packaged in the wrong directory! (`META-INFO/` instead of `META-INF/`), explaining why it works on Linux or Mac OS (the relative libraries are on right folder, `META-INF/`). The commit dbae5f81f3580c980bd9e2c52498e13e63e0139c, relocating these, seems to introduce this bug in [`bigtable-hbase-parent/bigtable-hbase-1.x-shaded/pom.xml`](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/dbae5f81f3580c980bd9e2c52498e13e63e0139c/bigtable-hbase-parent/bigtable-hbase-1.x-shaded/pom.xml#L151).

To fix the bug locally, we unpacked the jar, and repacked it with the `com_google_bigtable_repackaged_netty_tcnative_windows_x86_64.dll` in `META-INF/` and it works.

I think the error is the same with `bigtable-hbase-2.x-shaded`, because `META-INFO/` have probably been copy-pasted to the [`bigtable-hbase-parent/bigtable-hbase-2.x-shaded/pom.xml`](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/be8aa4505fd7ae1d42899924f9ff8b5f977265d5/bigtable-hbase-parent/bigtable-hbase-2.x-shaded/pom.xml#L214).

Can you please change `META-INFO/` to `META-INF/` in these two files? As of now, we fix it locally by manually repacking the jar, but obviously this is not a satisfying and maintainable solution.

I think this could solve many problems related to `bigtable-hbase-1.x`, since the error message thrown is not clear at all : this is not an `ALPN` problem, but more a shading issue.

**Comment by sduskis** [comment]
Ugh.  Thanks for the catch.  Would you be able to test a new SNAPSHOT if I deploy it?  I don't usually test on windows.

**Comment by norbjd** [comment]
Of course :smile: I could test on my colleague PC where we had the bug (I'm not using Windows neither :stuck_out_tongue:). Thanks for the reply, just tell me when you have deployed.

**Comment by sduskis** [comment]
The other shading has `libcom_google` as the prefix of the file.  Does windows work with just `com_google`?

**Comment by norbjd** [comment]
Yes, for our tests we kept `com_google` as before.

**Comment by sduskis** [comment]
I deployed a new SNAPSHOT.  See [this pom.xml](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/java/hello-world/pom.xml#L40) repository section for how to add the snapshot repo.

**Comment by norbjd** [comment]
We just checked and it works with the SNAPSHOT. Thanks, when do you think the release 1.2.1 will be available ?

**Comment by sduskis** [comment]
We'll hopefully release the next version sometime this week.  There are a handful of other issues we need to clean up that are still in progress.

**Comment by sduskis** [comment]
We still have an issue or two that's outstanding, but we're hopeful to get out the release in the next couple of days.
