### ISSUE TITLE
RefreshingOAuth2CredentialsInterceptor.TIMEOUT should be final

### ISSUE THREAD

**Issue by kluever** [GoogleCloudPlatform/cloud-bigtable-client#1775]
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/9f2e7206e3198cf3a1992dd8195925573fa64a09/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/io/RefreshingOAuth2CredentialsInterceptor.java#L58

Constants should be final, otherwise someone can easily write:
`RefreshingOAuth2CredentialsInterceptor.TIMEOUT = Duration.ZERO;`

**Comment by sduskis** [comment]
We originally intended that users ought to be able to modify this themselves.  We need a better way to do that.  Ideally, this timeout would be passed to the Credentials object somehome.

**Comment by kluever** [comment]
I'd **strongly** discourage the use of public static mutable fields, especially if it's being named like a `CONSTANT` (when it's non-final).

**Comment by sduskis** [comment]
ack.
