### ISSUE TITLE
Fix the name of AbstractBigtableRegionLocator

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/cloud-bigtable-client#1792]
[This class](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/ca3436353b4bdc78dc5a65b0751197609c53cf5b/bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/AbstractBigtbleRegionLocator.java) is currently named `AbstractBigtbleRegionLocator` (note the missing `a` in `Bigtable`).

**Comment by rupeshitpatekarq** [comment]
It is handled in PR #1794 hence closing.
