### ISSUE TITLE
Misspelled key in BigtableOptionsFactory

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/cloud-bigtable-client#1803]
A customer reported [another misspelled key](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/caf113e48bc9f9dc4cab20548ecc5ac67a94099b/bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableOptionsFactory.java#L277) in `BigtableOptionsFactory`. It should be `BIGTABLE_NAMESPACE_WARNING_KEY`, not `BIGTABLE_NAMESAPCE_WARNING_KEY`.

**Comment by sduskis** [comment]
Closed by #1811
