### ISSUE TITLE
Replication is no longer in alpha

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/cloud-bigtable-client#1865]
If you [search this repo for the phrase "Cloud Bigtable replication,"](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/search?q=%22Cloud+Bigtable+replication%22&unscoped_q=%22Cloud+Bigtable+replication%22) you'll see that a few classes still have the alpha disclaimer for replication. Now that replication is in beta, we can remove that disclaimer. (I don't think we normally put beta disclaimers in the API docs, and I don't see a reason to do so here; we used the alpha disclaimer because the feature wasn't available to everyone yet.)

**Comment by sduskis** [comment]
This was fixed by #1867.
