### ISSUE TITLE
Neither onError nor onComplete are called if a running request is cancelled

### ISSUE THREAD

**Issue by steveniemitz** [GoogleCloudPlatform/cloud-bigtable-client#1886]
Its possible this is intended behavior, but the behavior is surprising.

If I make an RPC call with `readFlatRows(ReadRowsRequest, StreamObserver<FlatRow>)`, and then cancel the call before it completes, neither `onComplete`, nor `onError` are ever raised for that call.  I would have expected `onError` to be called on my StreamObserver with something like a cancellation exception.

I'm using 1.3.0 currently, however I can't see any material difference between that an master, so I'd assume this bug still exists there.  

`completionFuture` (which is accessible via `getAsyncResult` on AbstractRetryingOperation) IS satisfied with an exception, so it seems like this might only effect the StreamObserver based API.

**Comment by sduskis** [comment]
I see the problem.  This should be quick to fix, but I'll need to add a bunch of tests to confirm the behavior.

**Comment by steveniemitz** [comment]
Awesome, thanks.  I'm experimenting now with just adding a call to `setException` in the CANCELLED case of onError, which seems like it should do the trick.

**Comment by sduskis** [comment]
I added tests, and performing a cancel seemed to work as expected regarding cancel.  [This line](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/1885/files#diff-0dbb7faf56b76359f92ab9f60f9c9eb5R203) in a PR that was merged today.  Can you please retry master to confirm?

**Comment by steveniemitz** [comment]
Cool, thats the same change I made.  I can't easily upgrade to master right now (due to lots of dependency changes) but I can confirm that change did fix it.
