### ISSUE TITLE
Allow configuration of Credentials via HBase.

### ISSUE THREAD

**Issue by hfgbarrigas** [GoogleCloudPlatform/cloud-bigtable-client#1895]
Can we add a constructor on BigtableAsyncConnection that accepts BigtableOptions? Feels weird that I can use the BigtableOptions builder and I'm forced to pass in Configuration from hbase.

Or am I missing something?

**Comment by sduskis** [comment]
In theory this is possible, but not something I'd like to do.

We think about the artifacts in `bigtable-client-core` as a stand alone client, and the HBase artifacts as adapters for the HBase interface.  The general configuration interface for HBase is a `Configuration` object, and that's what our HBase customers use either programmatically or via an `hbase-site.xml` file.  You can see the details of the conversion in the `BigtableOptionsFactory` class.

Is there a reason you don't want to use a `Configuration` object, and you want to use a `BigtableOptions` object?

**Comment by hfgbarrigas** [comment]
Looking at the code on `BigtableOptionsFactory` looks like `Configuration` can only deal with credentials provided either via json, file location and if none is used will default to `applicationDefault`. Since I already have `Credentials` available (another component deals with providing credentials), seems redundant to have to fetch them again. we could perhaps have a `toConfiguration(BigtableOptions)` ?

**Comment by sduskis** [comment]
`toConfiguration(BigtableOptions)` or a new Configuration won't work easily.  I'll talk with my colleagues, specifically @igorbernstein2, about some options for passing either `BigtableOptions` or some other mechanism for `Credential` passing.  Hopefully, we can think through an approach before our next release, which is imminent.

FWIW, We're changing to a new model in the near future that uses a new client [google-cloud-bigtable](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-bigtable).  This will impact some of our design decisions.

**Comment by sduskis** [comment]
#1899 is an attempt to allow you to set a `Credentials` object.  It uses reflection, and isn't perfect, but it's a lower impact change.  WDYT, @hfgbarrigas?
