### ISSUE TITLE
Provide a way to configure the underlying netty channels created in BigtableSession.

### ISSUE THREAD

**Issue by steveniemitz** [GoogleCloudPlatform/cloud-bigtable-client#1906]
Our service runs gRPC in the same process as other netty-consuming libraries (finagle).  A consequence of this is that we actually configure the gRPC netty channels to share the same event loop group as our other libraries.  We also use epoll, so I configure the netty channels for that as well.

I've done this by adding an overridable method in `BigtableSession` that I can override in my code and hook into the netty configuration.  This is a little hacky however, because there are two code paths, one for the public static `BigtableSession.createChannelPool` and one for the protected instance `createChannelPool`.  I'd be happy to submit a PR for this, but as I said my solution is a little hacky, and I think it might require some larger refactoring to remove the static methods here.

**Comment by sduskis** [comment]
We use the static methods elsewhere, which is probably the wrong thing to do.  We should probably separate concerns and create some sort of `ChannelBuilderFactory` or something like that.

**Comment by steveniemitz** [comment]
We should construct it via a `ChannelBuilderFactoryBuilder` as well ;)

On a serious note, I think thats a good idea, possibly set on `BigtableOptions`, with a default set that does what is already done now?

**Comment by sduskis** [comment]
`BigtableOptions` sounds like a good place to put this.  The only catch is that `BigtableOptions` needs to be completely `Serializable`.  I'll think about this for a bit.

**Comment by steveniemitz** [comment]
ack on `Serializable`, it should be fine though, most implementations should have no state and be trivially serializable.

**Comment by sduskis** [comment]
I'm ok with putting this on `BigtableOptions`.   I don't know if there's a cleaner way to do it.

**Comment by steveniemitz** [comment]
That'd be useful, the only issue there is that the current implementation uses some internal client interceptors when it creates the channel.

If I passed in a channel, would I also then be responsible for creating a pool?  We'd need to then expose that publicly as well.

**Comment by igorbernstein2** [comment]
The only interceptors that are per channel are the channel ids, which should be easy to replicate. All the over interceptors can be wrapped around the entire pool. 
Yes, you'd be responsible for creating the pool. I thought you had your own implementation of channel pooling (that preemptively reconnected channels)?

**Comment by igorbernstein2** [comment]
My current thought is that customizing the behavior of the channel pool needs to happen very rarely. It is mostly requested by customers with pretty advanced usecases, in most cases the customer has a very indepth understanding of the pool and have very specific needs. I feel like introducing a callback (builder factory) adds another layer of indirection and makes it a lot harder to reason about the initialization of the client in the general case. My preference would be to error on a cleaner separation at the cost of a bit of code duplication. 

In concrete terms it would mean that for the bigtable-client-core:
- we would pull all of the interceptors up to BigtableSession
- you would implement a ChannelFactory that creates configured channels
- you would wrap the factory in a [ChannelPool](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/io/ChannelPool.java)
- you would pass the ChannelPool to BigtableSession

For google-cloud-java, it's a bit more  complicated and I need a bit more time to think it through

**Comment by steveniemitz** [comment]
I think that makes a lot of sense, and would work for me!

wrt google-cloud-java, does that use gax-grpc?  I've done a similar thing for that already (and opened https://github.com/googleapis/gax-java/issues/573)

**Comment by igorbernstein2** [comment]
yep

**Comment by steveniemitz** [comment]
fun times!

**Comment by sduskis** [comment]
I'm going to close this.  Anything of this sort should be done in the new `google-cloud-bigtable` client.

**Comment by igorbernstein2** [comment]
As a side note, this has been implemented in the google-cloud-java client in 
https://github.com/googleapis/gax-java/pull/629
