### ISSUE TITLE
Potential ByteBuf memory leak

### ISSUE THREAD

**Issue by KaoruDev** [GoogleCloudPlatform/cloud-bigtable-client#1920]
Hi, using `com.google.cloud.bigtable:bigtable-hbase-1.x-shaded:1.5.0` and noticing these log errors: 

```
level=ERROR date=2018-08-29T20:11Z thread="grpc-default-worker-ELG-1-28" class=com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.util.ResourceLeakDetector message="LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information
```

which lead me here: http://netty.io/wiki/reference-counted-objects.html#troubleshooting-buffer-leaks

From what I gather, looks like the client may have a memory leak?

**Comment by sduskis** [comment]
Thanks for reporting this.  This sounds like a difficult problem.  We'll dig in to see what we can do about this.

**Comment by sduskis** [comment]
There are a [number of issues](https://github.com/grpc/grpc-java/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+bytebuf) in grpc related to this topic.  Our code doesn't open ByteBufs, but gRPC does.  I hope that the gRPC team can fix this, since I'm not sure our client can.

**Comment by sduskis** [comment]
There's nothing actionable here.  I'm going to close this.  Hopefully gRPC will fix this.
