### ISSUE TITLE
Linking of OpenCensus spans

### ISSUE THREAD

**Issue by hexedpackets** [GoogleCloudPlatform/cloud-bigtable-client#1929]
With the way tracing is currently implemented, some spans are created with `startScopedSpan` and some with `startSpan`. The ones created with `startSpan` are recorded independently of the calling code, and without making the span variable public there isn't any way to link it with a parent. For example, all of the gRPC operations use unscoped spans: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/AbstractRetryingOperation.java#L176

Is there a reason for using unlinked spans? If not, it would be great to switch to scoped spans and get the Bigtable operations linked.

**Comment by sduskis** [comment]
Thanks for the find.  All spans should be scoped.  @ajaaym, FYI.

**Comment by sduskis** [comment]
@bogdandrutu, do you have any guidance on this issue?

**Comment by sduskis** [comment]
@hexedpackets, it sounds like the library ought to be doing the right thing.  Did you see anything strange which prompted you to create the issue?

**Comment by hexedpackets** [comment]
I've been digging into the opencensus code and it looks like you're right about the parent spans being set. I think this might be an issue with wrapping spans around async calls - I think the parent span is ending before the bigtable client executes anything so the spans end up without their parent set. 

I'm still trying to verify that in my code, but does that sound plausible? Specifically, I'm looking at code that calls `BigtableSession.createBulkMutation` and then later calls `flush` on it.

**Comment by hexedpackets** [comment]
I'm not sure. My goal is to get a sense of how much time is being spent on Bigtable operations for a given input, but I think I'm realizing it may not be possible. From what you said and looking closer at our own code, there isn't a clear hierarchical relationship between a single input and a single set of Bigtable operations.

I'm going to close this out, thanks for helping me better understand what's happening.
