### ISSUE TITLE
.setLimit() has no effect on Scan?

### ISSUE THREAD

**Issue by jszule2** [GoogleCloudPlatform/cloud-bigtable-client#1933]
Hi,

I've tried to use the .setLimit() on a Scan, but it still returns with all rows in the table after the startrow.

Below the code snippet, which produces this error.

```java
public static void main(String[] args) throws IOException  {
    Connection c = BigtableConfiguration.connect(projectId, instanceId);
    Table t = c.getTable(TableName.valueOf(tableName));

    Scan s = new Scan().withStartRow(Bytes.toBytes(startRow)).setLimit(5);
    ResultScanner resultScanner = t.getScanner(s);
    
    for (Result r : resultScanner) {
        System.out.print(Bytes.toString(r.getRow()) + "\t");
        System.out.println(Bytes.toString(r.value()));
    }
}
```

Gradle dependecy: 
```
dependencies {
    implementation "com.google.cloud.bigtable:bigtable-hbase-beam:1.5.0"
}
```

I tried with different versions of Bigtable dependencies but the result was the same.

Do I misuse something? 

Thanks!

**Comment by sduskis** [comment]
We have not kept up with all of the features in newer HBase versions.  `setLimit` seems to have been added in HBase 1.4.  

For now, you can use a `PageFilter` to limit the number of records.  We'll find a way to use `setLimit` in Cloud Bigtable.

**Comment by jszule2** [comment]
Thank you for your answer! We will go with `PageFilter` in this case.
