### ISSUE TITLE
Fresh checkout is failing in windows 10 

### ISSUE THREAD

**Issue by rahulKQL** [GoogleCloudPlatform/cloud-bigtable-client#1960]
#### Bug:
After taking checkout of this project in **windows 10** platform,  I tried the same with two of my Windows 10 system. Maven build fails while building the project, it seems "TestBigtableOptions.testEmulator()" test case errors out with below message:
	
`Oct 08, 2018 3:44:34 PM com.google.cloud.bigtable.config.BigtableOptions info
INFO: Connecting to the Bigtable emulator at localhost:1234
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.61 sec <<< FAILURE! - in com.google.cloud.bigtable.config.TestBigtableOptions
testEmulator(com.google.cloud.bigtable.config.TestBigtableOptions)  Time elapsed: 0.044 sec  <<< FAILURE!
java.lang.AssertionError: expected:<443> but was:<1234>
        at com.google.cloud.bigtable.config.TestBigtableOptions.testEmulator(TestBigtableOptions.java:110)	
`

#### Observations:
 The cause of this issue is due to `TestBigtableOptions.setTestEnv()` is not refreshing the JVM's System variable for test this case.

Once get past this, two more test classes are failing i.e. `SequenceFileSinkTest.java` , `SequenceFileSourceTest.java` with respective error messages:

**SequenceFileSinkTest:**
`org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.nio.file.InvalidPathException: Illegal char <*> at index 61: C:\Users\Tblocks\AppData\Local\Temp\junit5611881403796920631/*`
	
**SequenceFileSourceTest:**
`java.lang.NullPointerException
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)`

#### Workaround:
To solve the `setTestEnv()` refreshing issue, just `clear()` the `theEnvironmentField` and `theCaseInsensitiveEnvironmentField` Map, something like this:
```java
    Map<String, String> env = (Map<String, String>) theEnvironmentField.get(null);
    env.clear();
    env.putAll(newEnv);
```

For other two test cases, I am still finding solution for them. For workaround we can use `@Ignore` on local test files.

**Comment by rahulKQL** [comment]
Thought of adding url to my findings [here](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/compare/master...rahulKQL:windows_build_issue)

**NOTE:** SequenceFileSourceTest is still not falling back to native library present in hadoop jars, as I think happens for other platform.

**Comment by sduskis** [comment]
We're not going to do antyhing about this for now.
