### ISSUE TITLE
KeyOnlyFilter shouldn't limit cells per row

### ISSUE THREAD

**Issue by mcorgan** [GoogleCloudPlatform/cloud-bigtable-client#1987]
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/3a8d06156681bf2c86a39fbb80c000a66cf05201/bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/filters/KeyOnlyFilterAdapter.java#L45

I think this is a mismatch with HBase's definition of the filter: https://hbase.apache.org/1.2/apidocs/org/apache/hadoop/hbase/filter/KeyOnlyFilter.html

"A filter that will only return the key component of each KV (the value will be rewritten as empty).
This filter can be used to grab all of the keys without having to also grab the values."

With the limit in place, it acts like a FirstKeyOnlyFilter.

**Comment by sduskis** [comment]
`KeyOnlyFilter` should just use the `cells_per_column_limit_filter` instead of `cells_per_row_limit_filter` filter.
