### ISSUE TITLE
FirstKeyOnlyFilterAdapter could strip value

### ISSUE THREAD

**Issue by mcorgan** [GoogleCloudPlatform/cloud-bigtable-client#1989]
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/3a8d06156681bf2c86a39fbb80c000a66cf05201/bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/filters/FirstKeyOnlyFilterAdapter.java#L32

Could this adapter also do FILTERS.value().strip() for potentially better performance?

**Comment by igorbernstein2** [comment]
Yes. We would very much appreciate this improvement. Would you mind opening a PR?
