### ISSUE TITLE
UTF8 strings as rowkeys

### ISSUE THREAD

**Issue by vc13819** [GoogleCloudPlatform/cloud-bigtable-client#2030]
Can the bigtable rowkey be arbitrary utf8, or its only ascii.
When I try to add utf8 strings e.g. "অবৈধ লগইন শংসাপত্রের" as the row key, the subsequent lookup fails.

Are such strings allowed as keys.

I am able to use them in values though.

**Comment by sduskis** [comment]
Cloud Bigtable only uses `ByteString` and `byte[]` as keys.  How did you create the original key?  That would help us understand how to help you perform subsequent lookups.

**Comment by vc13819** [comment]
The problem was with our code. We werent using character encoding while doing getBytes.
