### ISSUE TITLE
Cells ordering in FlatRow#getCells()

### ISSUE THREAD

**Issue by nezdolik** [GoogleCloudPlatform/cloud-bigtable-client#2033]
in [FlatRow](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/scanner/FlatRow.java) implementation when calling <code>FlatRow#getCells()</code>, can we rely that list of cells is ordered by <code>Cell#timestamp</code> ? Or the caller needs to sort Cells by timestamp?

**Comment by sduskis** [comment]
Cells are ordered as follows:

1. Column Family, lexicographically ascending
2. Qualifier, lexicographically
3. timestamp, descending

**Comment by nezdolik** [comment]
@sduskis Thanks a lot for explanation
