### ISSUE TITLE
bigtable client is too big for new App Engine 

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/cloud-bigtable-client#2039]
Getting this error while trying to adapt a sample to the new coming GAE Java runtime, which does not have a stage phase that can split jars (idiomatic runtime, using the Cloud SDK as is):

GCLOUD: ERROR: (gcloud.app.deploy) Cannot upload file [/Users/ludo/a/samples/bigtable/target/appengine-staging/hbase-shaded-client-1.4.5.jar], which has size [34971024] (greater than maximum allowed size of [33554432]). Please delete the file or add to the skip_files entry in your application .yaml file and try again.

I know there is a bug open on the deployment pipeline, but I see no traction for it... Could it be possible to cut this Jar in 2 smallers at the cloud bigtable client dependency level?

**Comment by sduskis** [comment]
That's unfortunate, but I don't believe we can fix that issue with the HBase client.

We have a new client (google-cloud-bigtable) in https://github.com/GoogleCloudPlatform/google-cloud-java that is likely to be a better fit for AppEngine.

@igorbernstein2, FYI

**Comment by sduskis** [comment]
Alternatively, you can try to include the `com.google.cloud.bigtable:bigtable-hbase-1.x-hadoop` which should have smaller jars.

**Comment by ludoch** [comment]
Compiling and deploying with x-hadoop version seems to make the trick. Now I can continue my testing on the prod side. 

Thanks.

**Comment by igorbernstein2** [comment]
Can you describe your usecase? I'd like to understand your desire to use an habse compatibility layer in app engine

**Comment by ludoch** [comment]
use case is that the current GAE Cloud SDK based deployement has a limit of 32Mb per artifact...
Without client processing to reduce jars over 32Mb, you cannot deploy your application.

**Comment by igorbernstein2** [comment]
Sorry being unclear.
I would like to understand your preference of using the hbase apis in bigtable-hbase-X over the native apis in bigtable-client-core or the google-cloud-java.

**Comment by ludoch** [comment]
No preferences.... But all our samples so far were using this lirary, not the google-cloud-java....

Just tried it, and of course, it does not compile as my sample depends on org.apache.hadoop imports...
Do you have a similar samples with google-cloud-java (and what is the confidence level for a 0.75 alpha version for promoting it?)

**Comment by sduskis** [comment]
@igorbernstein2, and @ajaaym, it sounds like we ought to modify our existing AppEngine CBT examples, or create new ons for google-cloud-java.

**Comment by sduskis** [comment]
@igorbernstein2, our examples couldn't use `bigtable-client-core`, since we don't officially support it.

**Comment by ludoch** [comment]
The sample works...

Getting this type of warning:
A  WARNING: An illegal reflective access operation has occurred 
A  WARNING: Illegal reflective access by org.apache.hadoop.hbase.util.UnsafeAvailChecker (file:/srv/hbase-common-1.4.5.jar) to method java.nio.Bits.unaligned() 
A  WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.hbase.util.UnsafeAvailChecker 

but functional. Thanks for your help!

**Comment by ludoch** [comment]
For the record, F2 instance class size is a bit small, so used F4.
