### ISSUE TITLE
The ClientWrapper should use model.Row instead of FlatRow

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#2077]

**Comment by rahulKQL** [comment]
Current workaround would be to use [FlatRowAdpater](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/scanner/FlatRowAdapter.java#L31) with GCJ's BigtableDataClient#readRowCallable.

**Comment by sduskis** [comment]
We determined that `FlatRow` is acceptable.
