### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by zzaoen** [GoogleCloudPlatform/cloud-bigtable-client#2113]
Hi, 
I can't create bigtableOptions like following.
BigtableOptions.Builder()
        .setUserAgent("fake")
        .setProjectId("fakeproject")
        .setInstanceId("fakeinstance")
        .build();
Cloud SDK version is 236.0.0 and google-cloud-bigtable version is 0.81.0-alpha.
What's wrong with that?

**Comment by rahulKQL** [comment]
You should be able to get an instance of `BigtableOptions` with default host & port. If you want to connect to emulator then please provide it's host & port along.

Could you please be more specific If anything otherwise.

**Comment by sduskis** [comment]
@zzaoen, `BigtableOptions` is for the client in this repository, which is in the `bigtable-client-core` artifact, which is being deprecated.  You're using `google-cloud-bigtable`, which is our new client.

Please see here for how to use `google-cloud-bigtable`: https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-bigtable#getting-started

**Comment by zzaoen** [comment]
Thank you guys.
I've solved this problem. I didn't add **bigtable-hbase** in pom.xml.

**Comment by zzaoen** [comment]
> @zzaoen, `BigtableOptions` is for the client in this repository, which is in the `bigtable-client-core` artifact, which is being deprecated. You're using `google-cloud-bigtable`, which is our new client.
> 
> Please see here for how to use `google-cloud-bigtable`: https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-bigtable#getting-started

I've tried new client API, and It works(access cloud bigtable). But did you mean new client API can directly access bigtable emulator ? I started bigtable emulator and export BIGTABLE_EMULATOR_HOST, but my java code would still connect to cloud bigtable, rather than local emulator? 

I didn't find BigtableOptions can set relevant variable like DatastoreOptions
DatastoreOptions options = DatastoreOptions.newBuilder()
                .setProjectId(DatastoreOptions.getDefaultProjectId())
                .setHost(System.getenv("DATASTORE_EMULATOR_HOST"))
//                .setCredentials(NoCredentials.getInstance())
                .setRetrySettings(ServiceOptions.getNoRetrySettings())
                .build(); 

https://github.com/googleapis/google-cloud-java/blob/master/TESTING.md#testing-code-that-uses-bigtable
This page didn't tell me how to use new API to connect to Bigtable emulator, do you know where I can get some sample codes? Thanks a lot!

**Comment by sduskis** [comment]
Yes, the new client can use the emulator. The new client has a feature where you can start the emulator from Java, rather than using a command line.

You can see the full example here: https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-testing/google-cloud-bigtable-emulator
