### ISSUE TITLE
Shouldn't Cluster.hdd_bytes and Cluster.ssd_bytes be in a oneof block?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/cloud-bigtable-client#366]
I'm implementing the Python library for the API and noticed that both `hdd_bytes` and `ssd_bytes` can be set on a `CreateCluster` call (and they persist when calling `GetCluster`).

Shouldn't the values (in the `Cluster` [message class][1]) be in a [`oneof` block][2]:

```
  // The maximum HDD storage usage allowed in this cluster, in bytes.
  int64 hdd_bytes = 6;

  // The maximum SSD storage usage allowed in this cluster, in bytes.
  int64 ssd_bytes = 7;
```

[1]: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/abe13c41f6df8e3659edffc86ea2feee678b8363/bigtable-protos/src/main/proto/google/bigtable/admin/cluster/v1/bigtable_cluster_data.proto#L82-L86
[2]: https://developers.google.com/protocol-buffers/docs/proto#oneof

**Comment by mgarolera** [comment]
The cluster api is not currently enabled. There will be some iteration on it. This fields are likely to not be used any time soon, prefer using only default_storage_type instead.

Right now clusters are only created via the UI and a cluster can only be SSD. In the future we plan to enable HDD clusters, and maybe one day mixed HDD and SSD in the same cluster, which would make these fields meaningful.

**Comment by jgeewax** [comment]
OK.

This leads to a second question. If we were to send a pull request to modify these protos, would it be worthwhile? Or is this "read-only" open source that will have changes blasted out during some sync job?

**Comment by dhermes** [comment]
Thanks for the reply @mgarolera !

Regarding

> The cluster api is not currently enabled.

I have been able to use it (with a user account, not with a service account) when enabling the "Cloud Bigtable Table Admin API" in the APIs console. See GoogleCloudPlatform/gcloud-python#872 for discussion.

----

@jgeewax It doesn't seem we'd want to make a PR for this issue.

**Comment by mgarolera** [comment]
@jgeewax: Yes, there protos are not yet the authoritative source and a change would be overwritten.
@dhermes: The api shouldn't be enabled for external users. If you are writing tooling to use it, don't use hdd_bytes and ssd_bytes. HDD clusters are coming soon so it would be useful to be able to control the default_storage_type field.

**Comment by dhermes** [comment]
Thanks @sduskis!
