### ISSUE TITLE
mvn Shield like gcloud-java

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/cloud-bigtable-client#387]
It would be great if we had a release shield, like they have for https://github.com/GoogleCloudPlatform/gcloud-java [![Maven](https://img.shields.io/maven-central/v/com.google.gcloud/gcloud-java.svg)]( https://img.shields.io/maven-central/v/com.google.gcloud/gcloud-java.svg)

They appear to be using the service http://shields.io/

**Comment by sduskis** [comment]
What's the benefit of a maven shield?

**Comment by lesv** [comment]
Makes it easier for folks to do what the readme is telling them to do.  gcloud-java has chosen to do it.

**Comment by lesv** [comment]
It's the equivalent of you updating the README, but it happens automatically.

**Comment by sduskis** [comment]
@lesv: I added a bunch of shields... Can you PTAL?

**Comment by lesv** [comment]
Very nice - Thanks.
