### ISSUE TITLE
Add size estimate for regionLocator. 

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#400]
This will help with CDF integration.

**Comment by mbrukman** [comment]
This issue is referenced from the [Bigtable/Dataflow integration README](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/tree/master/bigtable-dataflow-parent/bigtable-hbase-dataflow#reading) where it says:

> The Bigtable Source is not fully optimized for use in Dataflow, but is (or at least should be) functional for your use. It will be improved when issue #400 is resolved.

Was this bug fixed? There's no PR attached to it.

Can that text be removed?

**Comment by sduskis** [comment]
We should update the text to say that Cloud Bigtable doesn't use dynamic rebalancing, but will work well.

**Comment by sduskis** [comment]
I don't think that we can fix this.  RegionLocator doesn't have a size estimate.  ClusterStatus does have a size estimate, but is not compatible with the way Cloud Bigtable calculates sizes.
