### ISSUE TITLE
Javadoc build target is not working correctly

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/cloud-bigtable-client#452]
For some reason (I can't figure out why), commit 3eb991f4fe591bc08bd7c7ae6670fcd42ecaec07 broke the "offline links" functionality in the Javadoc build target. As a result, the API docs no longer link to the HBase and Dataflow docs. The API docs also show the fully qualified name of each HBase and Dataflow class, which ends up looking silly.

For example, here's how the `CloudBigtableIO` method summary is supposed to look:
![screen shot 2015-09-01 at 3 29 54 pm](https://cloud.githubusercontent.com/assets/1522391/9618906/4180ea20-50bf-11e5-8f9c-e86dfa6eed65.png)

Here's how it looks after 3eb991f4fe591bc08bd7c7ae6670fcd42ecaec07 (there's some slight wonkiness because I had to assemble the image in Photoshop--the table doesn't all fit on one screen):
![screen shot 2015-09-01 at 3 30 45 pm copy](https://cloud.githubusercontent.com/assets/1522391/9618917/59a491c4-50bf-11e5-9ffb-875906d285aa.png)

**Comment by sduskis** [comment]
This was fixed.
