### ISSUE TITLE
Use SampleRowKey sizes into ClusterStatus

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#483]

**Comment by mgiambalvo** [comment]
For context, this is needed for Impala so it can do query planning. Previously, Impala would read the size of the storefiles in HDFS. We need a way to get the region sizes from SampleRowKeysResponse, similar to how the [dataflow integration works](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/39f6e0c8e481303ddba785484929affd9021f26e/bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/CloudBigtableIO.java#L485).

**Comment by sduskis** [comment]
This isn't going to work for cloud bigtable.
