### ISSUE TITLE
SLF4J can't load logger binding

### ISSUE THREAD

**Issue by gamorris** [GoogleCloudPlatform/cloud-bigtable-client#507]
On start up running with bigtable client libraries:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by kevinsi4508** [comment]
Where did u see this error? I am getting a similar error.

**Comment by sduskis** [comment]
The answer here is to have a log4j.properties file, or something similar.  We added a few.
