### ISSUE TITLE
TTL not working, still able to get value after TTL reached

### ISSUE THREAD

**Issue by reagere** [GoogleCloudPlatform/cloud-bigtable-client#529]
Hello,

We found an issue with bigtable, where the table as a ttl to one minute, but the value inserted not deleted.

```
'testBBO', {NAME => 'cd', BLOOMFILTER => 'ROW', VERSIONS => '1', IN_MEMORY => 'false', KEEP_DELETED_CELLS => 'FALSE', DATA_BLOCK_ENCODING => 'NONE', TTL => '60 SECONDS (1 MINUTE)', COMPRESSION => 'NONE', MIN_VERSIONS => '0', BLOCKCACHE => 'true', BLOCKSIZE => '65536', REPLICATION_SCOPE => '0'}
150 : 1
10361 : 1
20470 : 1
30594 : 1
40670 : 1
50780 : 1
60811 : 1 // should be deleted
70857 : 1
80980 : 1
91104 : 1
101225 : 1
111294 : 1
121351 : 1
131366 : 1
...
10 minutes later still here
```

Here is the code used:
```java
package com.accengage.bigdata.test.bigtable;

import java.io.IOException;

import org.apache.hadoop.hbase.HColumnDescriptor;
import org.apache.hadoop.hbase.HTableDescriptor;
import org.apache.hadoop.hbase.TableName;
import org.apache.hadoop.hbase.client.Admin;
import org.apache.hadoop.hbase.client.Get;
import org.apache.hadoop.hbase.client.Put;
import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.client.Table;
import org.apache.hadoop.hbase.util.Bytes;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import com.accengage.bigdata.db.bigtable.Bigtable;

public class BigtableTtl {

	private static TableName tableName = TableName.valueOf("testBBO");
	private static Admin admin;
	private static long debut;

	/**
	 * delete test table, close hbase connection
	 *
	 * @throws IOException
	 */
	@AfterClass
	public static void clean() throws IOException {
		deleteTestTable();
		Assert.assertFalse(admin.tableExists(tableName));
		admin.close();
		Bigtable.getInstance().close();
	}

	/**
	 * create hbase connection, create test table, fill data
	 *
	 * @throws IOException
	 */
	@BeforeClass
	public static void setup() throws IOException {
		final Bigtable bigtable = Bigtable.getInstance();
		admin = bigtable.getAdmin();
		deleteTestTable();
		Assert.assertFalse(admin.tableExists(tableName));
		HColumnDescriptor hcolDesc = new HColumnDescriptor(Bytes.toBytes("cd"));
		hcolDesc.setTimeToLive(60);
		final HTableDescriptor htableDescriptor = new HTableDescriptor(tableName);
		htableDescriptor.addFamily(hcolDesc);
		admin.createTable(htableDescriptor);
		Assert.assertTrue(admin.tableExists(tableName));
		fillTable();
	}

	private static void deleteTestTable() throws IOException {
		if (admin.tableExists(tableName)) {
			if (admin.isTableEnabled(tableName)) {
				admin.disableTable(tableName);
			}
			admin.deleteTable(tableName);
		}
	}

	private static void fillTable() throws IOException {
		final Bigtable bigtable = Bigtable.getInstance();
		Table table = bigtable.getTable(tableName);
		Put put = new Put(Bytes.fromHex("abcdef"));
		put.addColumn(Bytes.toBytes("cd"), Bytes.toBytes("counter"), Bytes.toBytes(1L));
		table.put(put);
		debut = System.currentTimeMillis();
		System.out.println(admin.getTableDescriptor(tableName));
	}

	@Test
	public void testTtl() throws IOException, InterruptedException {
		Get get = new Get(Bytes.fromHex("abcdef"));
		Table table = Bigtable.getInstance().getTable(tableName);
		for (int i = 0; i < 60; i++) {
			Result result = table.get(get);
			byte[] v = result.getValue(Bytes.toBytes("cd"), Bytes.toBytes("counter"));
			System.out.println((System.currentTimeMillis() - debut) + " : " + (v != null ? Bytes.toLong(v) : "null"));
			synchronized (this) {
				wait(10000);
			}
		}
	}
}
```

We are using the driver 0.2.1 with hbase 1.1.1.

Thank you

**Comment by sduskis** [comment]
I think that this is intended behavior on the server side.  We only delete for TTL during major compactions, and reading does *not* currently skip expired values.

**Comment by reagere** [comment]
Hello,

For the get, I think I can manage by getting the timestamp of the version.

But for a filter, it is falsing the result:

```java
@Test
	public void testFilterTtl() throws IOException, InterruptedException {
		Scan scan = new Scan();
		scan.setFilter(new SingleColumnValueFilter(Bytes.toBytes("cd"), Bytes.toBytes("counter"), CompareOp.EQUAL, Bytes.toBytes(1L)));
		Table table = Bigtable.getInstance().getTable(tableName);
		for (int i = 0; i < 8; i++) {
			ResultScanner resultScan = table.getScanner(scan);
			Result result = resultScan.next();
			System.out.println((System.currentTimeMillis() - debut) + " : " + (result != null ? Bytes.toHex(result.getRow()) : "null"));
			synchronized (this) {
				wait(10000);
			}
		}
	}
```

Result:
```
'testBBO', {NAME => 'cd', BLOOMFILTER => 'ROW', VERSIONS => '1', IN_MEMORY => 'false', KEEP_DELETED_CELLS => 'FALSE', DATA_BLOCK_ENCODING => 'NONE', TTL => '60 SECONDS (1 MINUTE)', COMPRESSION => 'NONE', MIN_VERSIONS => '0', BLOCKCACHE => 'true', BLOCKSIZE => '65536', REPLICATION_SCOPE => '0'}
225 : abcdef
10305 : abcdef
20374 : abcdef
30408 : abcdef
40422 : abcdef
50440 : abcdef
60460 : abcdef
70484 : abcdef
```

**Comment by benjumanji** [comment]
So to be clear TTLs are more intended to be used like:

- You have some timeseries-y like data, and you always query ranges like `[T-6months, T)`. 
- As time marches on your query will be ignoring lots of data so you set a TTL for say 8 months.
- As your application doesn't read those records anyway, it doesn't really matter when they actually get reaped.

And they are definitely _not_ to be used as a proxy for filtering.

Seems OK to me. That's mostly how I use TTLs in Cassandra even if it actually has slightly more precise GC.

**Comment by reagere** [comment]
From HBase point of view: ColumnFamilies can set a TTL length in seconds, and HBase will automatically delete rows once the expiration time is reached. This applies to all versions of a row - even the current one. The TTL time encoded in the HBase for the row is specified in UTC.

(time is reached)

From bigtable point of view: TTL: The time to live, in seconds, for values stored in the column family. Values are deleted after this time.

(after ttl, could be weeks...)

From my point of view : it is not very hard to check ```(isFiltered(cell) && (hasNoTtl(cell) || isTtlOk(cell))```
For Google that means less bandwidth spent for nothing but a little more CPU spent when TTL is defined.

Here was the main idea for this proxy shortcut : We wanted to speed up the check of the presence of and type of event that occurred for the last 1 hour, 24 hour, 7 days, 31 days.
So instead of browsing all timeseries for 7 days, the simple fact that the 7day-event exists means that at least one event happened for the last 7 day.

1 value tested vs potential of millions events stored.

So we will fetch the timeseries...

**Comment by dmmcerlean** [comment]
@reagere: It's not clear to me why TTL is helpful for this, why can't you just fetch the most recent version and check its age?

In general, if your concern is returning too much data from your requests, it should be easy to use Scan.setTimeRange() to restrict the query to cells within the family TTL. It's true that it's not especially hard to perform this check on our side, but there are both performance and correctness ramifications if we do so:

1) From a performance standpoint, we now need to look up additional information about the table on *every* read, which is a non-negligible latency hit even for users who don't set any TTLs.

2) From a correctness standpoint, lengthening the TTL on a family would cause apparently "deleted" data to reappear, as we would have been hiding some of it without having actually reaped it from the underlying files. This has the potential to cause more serious problems than deleting things more slowly than expected. Worse yet, there could be a period of oscillation between the two cases if we aren't careful to look up the table metadata consistently, which compounds the performance problems mentioned above.

The first point can be partially mitigated with a change in our internal architecture, which is non-trivial but will likely be needed for other reasons anyway. However, the second point is trickier, and it's not clear that there's a solution to it that will satisfy everyone.

As a side note, standard HBase may not handle things quite as you might like. For max_versions at least (we haven't tested TTL), HBase actually rejects unreaped but "deletable" cells *after* running them through filters, not before. So from the perspective of a SingleColumnValueFilter, for example, an apparently "deleted" cell could still "exist."

**Comment by reagere** [comment]
Hello,

I think it is useful as the number of rows fetched is lower, the amount of data too and you spend less time with another step of filtering.

If I understand your point, I need to browse all the table to check if the last cell is part of my time range or not.

If you want to know quickly if you have an event for the last 7 days, TTL is (in the spec) a solution.

We do filtering for custom time periods, we fetch the data with MultipleColumnPrefix (time is in the column qualifier, and we use multiple column families) We just wanted to speed up common requests.

Thank you
