### ISSUE TITLE
ResultScannerBlocking

### ISSUE THREAD

**Issue by benjumanji** [GoogleCloudPlatform/cloud-bigtable-client#535]
request for method:

Could we add a `bool mightBlock()` to the ResultScanner?

Why? I would like to be able to wrap the scanner with something like a `Spool[T]` from twitter util which is essentially a linked list with the tail as `Future[T]`. The trick to not making this ungodly efficient is to only make a new task to be deferred only when one needs to. An example: 

https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/main/scala/com/websudos/phantom/iteratee/ResultSpool.scala

(NB: I am actually the author of that code see [here](https://github.com/websudos/phantom/pull/191/files))

I think for the current impl backed by a blocking queue this is as simple as adding a method that calls `isEmpty()` on the underlying queue. I'd be happy to contribute a patch if you guys are ok with the idea in principle.

**Comment by sduskis** [comment]
+1 on this.  This will help with some other issues we're having relating to long running scans.
