### ISSUE TITLE
BigTable should repackage io.grpc ?

### ISSUE THREAD

**Issue by christian-lefty** [GoogleCloudPlatform/cloud-bigtable-client#582]
It appears that the hbase bigtable jar is shipping a version of the io.grpc.protobuf.ProtoUtils
that's been shaded to operate on com.google.bigtable.repackaged.com.google.protobuf.*
messages.

This makes it impossible to build applications that are using both BigTable and GRPC (since our own classes need a version of ProtoUtils that works om com.google.protobuf.Messages)

My impression is that BigTable's ProtoUtils should be repackaged too to a private package?

**Comment by christian-lefty** [comment]
By the way there seems to have other issues too.

google.com.oauth.* should be repackaged or it conflicts with projects using protobufs.

**Comment by kevinsi4508** [comment]
Thanks Chris! We will work on the fix.

**Comment by sduskis** [comment]
I updated the pom.xmls, and this may work for you.  That said, if you're comfortable working with protobufs, and are willing to modify some code (hopefully slightly) in the near future, you can use the bigtable-client-core artifacts which don't need the hbase induced shading.

HBase uses old versions of protubuf, guava and some other libraries, and grpc uses newer versions.  We shaded the grpc dependencies into our bigtable-hbase-1.* jars to get around that problem.
