### ISSUE TITLE
Make AbstractCloudBigtableTableWriteFn public & rename

### ISSUE THREAD

**Issue by derjust** [GoogleCloudPlatform/cloud-bigtable-client#607]
The class `AbstractCloudBigtableTableWriteFn` provides connection pool managment for situations that go beyond batch-read/writing.

Right now the class is package-private and has 'Write' in its name whereas the class has no writing-functionality.
It would be great to have this class public & generic named to be used as starting point for complex `DoFn`s - like processing the output of a `Scan` while aggregating with additional data from `Get`s.

**Comment by sduskis** [comment]
Good suggestion.  I merged this change, and will submit an 0.2.3-SNAPSHOT shortly.

**Comment by sduskis** [comment]
I pushed a new SNAPSHOT.  Closing the issue.  Please reopen if need be.
