### ISSUE TITLE
What's the purpose of the BigTable client if you can also use HBase client? 

### ISSUE THREAD

**Issue by c4milo** [GoogleCloudPlatform/cloud-bigtable-client#786]
The README explains very well BigTable's benefits but not the purpose for this client. Why would someone use this client instead of the HBase one?  Or what exactly this client is extending in addition to what the HBase client provides?

**Comment by c4milo** [comment]
Found it https://cloud.google.com/bigtable/docs/hbase-differences

**Comment by sduskis** [comment]
FWIW, this repository contains both a stand alone client and the hbase adapter.

**Comment by c4milo** [comment]
Weird,  https://cloud.google.com/bigtable/docs/hbase-api-changes says TableName exists since HBase 1.0. I downloaded `bigtable-hbase-1.1-0.2.4.jar` and `hbase-client-1.2.0.jar` and this class doesn't seem to exist in any of them. What am I missing?

**Comment by sduskis** [comment]
It's in hbase-common.  Here's the file on github: https://github.com/apache/hbase/blob/master/hbase-common/src/main/java/org/apache/hadoop/hbase/TableName.java

**Comment by c4milo** [comment]
thanks @sduskis! I would have been easier if I could use maven, but the project I'm working on started without it :/
