### ISSUE TITLE
hadoop-common dependency missing

### ISSUE THREAD

**Issue by c4milo** [GoogleCloudPlatform/cloud-bigtable-client#788]
When installing with Ivy, hadoop-common does not get downloaded.

**Comment by c4milo** [comment]
See also http://stackoverflow.com/questions/35437237/class-not-found-in-cloud-bigtable-sdk

**Comment by sduskis** [comment]
The dependency is here: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-hbase-1.0/pom.xml#L47

I'm not sure how to make that work in ivy and sbt.  It probably relates to the way we're using the maven parent pom to manage versions.

**Comment by c4milo** [comment]
ah, I see, I think it is not a big deal as long as there is documentation somewhere talking about this. For now, I ended up adding the dependency directly in my Ivy config file.

**Comment by igorbernstein2** [comment]
This should no longer be an issue with the new 1.x artifacts. None of them exclude hadoop/hbase deps.

The new artifacts are:

bigtable-hbase-1.x: depends on hbase-shaded-client and exposes grpc and modern version of protobuf. This artifact is meant for standalone usage in webapps, beam, and other environments where the user is in control of their dependencies. This contains the actual connection implementation for hbase 1. It doesn't require any shading and allows for source navigation in ides. This should be the default choice for most users.

bigtable-hbase-1.x-shaded: this artifact doesn't contain any java source files, but uses the maven shade plugin to relocate all internal dependencies. This is meant for environments where the user is not in control of their dependencies and is mostly an implementation detail for dataflow 1.x that will eventually be deprecated in favor of beam. Source navigation will be partially broken for this artifact: you will be able to navigate to the hbase connector code, but navigation to the underlying core client will be broken. However this is just a stopgap measure until we transition to beam.

bigtable-hbase-1.x-hadoop: this is similar the -shaded variant but exposes Hadoop compatible dependencies. This is meant to be used in mapreduce jobs where the mapreduce framework injects jars into the user'a classpath. This will have similar limitations as the -shaded variant: you will be able to navigate to hbase compatibility code, but not the underlying core client. Unfortunately I don't think this is something we can do anything about. I would appreciate any suggestions.
