### ISSUE TITLE
Add way to filter on exact rows to RowFilter so that it can be used in Conditions

### ISSUE THREAD

**Issue by udoprog** [GoogleCloudPlatform/cloud-bigtable-client#801]
Hey,

I'm using the proto definitions available here as reference:
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/tree/master/bigtable-protos/src/main/proto/google/bigtable/v1

I have a use-case where I'd like to scan over a set of subsequent rows but filter out some columns with a range on the first and the last row. This sounds like a suitable case for Condition, however it's not clear how to make it match columns in only the first and last rows using a `RowFilter` predicate.

The columns are not organized in a way that allows for a single ColumnRange to be applied since qualifiers are repeated across rows. You can think of it like this:

```
row1 -> | q1 | q2 | ... | qN |
row2 -> | q1 | q2 | ... | qN |
row3 -> | q1 | q2 | ... | qN |
```

And I'd like to scan over `(row1, q4)` to `(row3, q2)` (`(<rowKey>, <columnQualifier>)`):
```
row1 -> | q4 | ... |  qN |
row2 -> | q1 | q2 | ... | qN |
row3 -> | q1 | q2 |
```

Currently I'm using `RowRange` in the target for `row1 ... row3` and filter out columns on the client. This is not optimal since I'm sending more columns to the client than what is strictly necessary.

I'd suggest the following:

1. Introduce a companion field for `RowFilter` called `row_key_filter`, which matches all columns if the current row key matches exactly. This complements `row_key_regex_filter` which is almost impossible to use correctly on binary keys.
2. Extract `target` from `ReadRowsRequest` into a new type and add that as a `RowFilter`, e.g. `target_filter`. Giving the above approach more flexibility.

**Comment by sduskis** [comment]
This sounds like an unusual case, and one we don't envision supporting on the server-side at this point.  We recommend the following:

A) Client side filtering (which you're doing), or 
B) issue a scan for the intermediate rows and point reads for the first and last row using the altered filters.

Is the cost of A) prohibitively expensive in your case?

**Comment by udoprog** [comment]
Client side filtering is fine:ish. I'm currently working to optimize the query path and one of my edge cases is this. So this would mostly be an improvement.

**B)** sounds interesting. From what I understand Bigtable will attempt to opportunistically load subsequent rows to reduce latency. If so, how will the point reads affect this?

**Comment by sduskis** [comment]
We're not 100% sure about the affects, but we think that it should still be in affect.  The opportunistic loading isn't directly tied to Cloud Bigtable API calls.

**Comment by udoprog** [comment]
Possibly mark as wishlist? If this was supported it would simplify a fair bit of client code for me.
