### ISSUE TITLE
Apache Beam is asking for an unbounded source for Bigtable

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/cloud-bigtable-client#837]
https://issues.apache.org/jira/browse/BEAM-45

"_Google Cloud Bigtable is currently in Beta. https://cloud.google.com/bigtable/ A bounded source is included in the initial code for Beam, and does a table scan (with an optional row filter) and dynamic work rebalancing._

_The unbounded source should support initial splitting based on key ranges but then streaming along the timestamp dimension_."

**Comment by lesv** [comment]
Also on SO http://stackoverflow.com/questions/37153513/bigtable-data-trigger-watch

**Comment by lesv** [comment]
@sduskis @carterpage FYI

**Comment by sduskis** [comment]
We don't have an API for this yet, AFAIK.

**Comment by sduskis** [comment]
This isn't feasible.  I'm closing this.
