### ISSUE TITLE
connection error in tomcat8

### ISSUE THREAD

**Issue by harbris** [GoogleCloudPlatform/cloud-bigtable-client#879]
I found connetion error in tomcat8.

`[DEBUG] 2016-06-15 16:24:19 com.google.cloud.bigtable.grpc.BigtableSession (Logger.java:39) - OpenSSL available: false
[DEBUG] 2016-06-15 16:24:19 com.google.cloud.bigtable.grpc.BigtableSession (Logger.java:39) - Jetty ALPN available: false
[ERROR] 2016-06-15 16:24:19 com.google.cloud.bigtable.grpc.BigtableSession (Logger.java:69) - Neither Jetty ALPN nor OpenSSL are available. OpenSSL unavailability cause:
java.lang.UnsatisfiedLinkError: no netty-tcnative in java.library.path
`

but It does work well in tomcat7.

**Comment by sduskis** [comment]
I'm not sure what the difference is between tomcat7 and tomcat8 in this case.  I would suggest adding netty-tcnative-boringssl-static to your classpath, as discussed [here](https://cloud.google.com/bigtable/docs/using-maven#encryption).

**Comment by harbris** [comment]
I already include in pom.xml.  
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>1.1.33.Fork13</version>
      <classifier>linux-x86_64</classifier>
    </dependency>

**Comment by sduskis** [comment]
Ugh.  This SSL setup is a bit beyond me.  I'll ask the grpc folks to see if they can help out.

The tc in tcnative stands for tomcat, so there could be some kind of conflict between the io.netty forked tcnative and something in tomcat8.

**Comment by lesv** [comment]
In Jetty, we had to add stuff to the system path, I suspect you are running into something similar in Tomcat.

If this is still an issue, please comment on the thread, and I'll setup an example.

**Comment by sduskis** [comment]
This is a classpath issue in tomcat.  I haven't been able to find an answer, and I'm not sure I have the means to do it.  I'm going to close this, since this is seemingly not directly a cloud-bigtable-client issue.  I'm sorry you've had these issues.
