### ISSUE TITLE
Bigtable dataflow counters don't get named properly when using multiple forks in the pipeline

### ISSUE THREAD

**Issue by ankurcha** [GoogleCloudPlatform/cloud-bigtable-client#894]
I have a pipeline where `CloudBigtableIO.writeToTable(config)` is called on multiple forks of the dataflow pipeline. Event when each of the transforms are specified with a name `.apply(this.getName() + ".WriteToBigTable", CloudBigtableIO.writeToTable(config))`, the `mutations` counters do not get the fully qualified name.
<img width="488" alt="screen shot 2016-06-28 at 1 33 27 am" src="https://cloud.githubusercontent.com/assets/124104/16409191/27920b7c-3cd1-11e6-877a-cd3ba71d9150.png">

I would expect the mutation counters to have the enclosing PTransform's name as a prefix (or something similar) that would make it easy to distinguish which fork of the transform the counters correspond to.

**Comment by sduskis** [comment]
@dhalperi: do you have any suggestions?

**Comment by dhalperi** [comment]
@ankurcha -- a Dataflow Job ID would help here

I'll ask some colleagues.

**Comment by ankurcha** [comment]
@dhalperi Job id: `2016-06-29_22_45_16-13259634448643607002`
Please let me know if you have any specific questions.

**Comment by dhalperi** [comment]
Hi Ankur,

It looks like this is a known issue and no fault of yours. Even though you have only applied CloudBigtableIO.Write twice, we are actually running many different copies of it through [Dataflow's fusion](https://cloud.google.com/dataflow/service/dataflow-service-desc#fusion-example). In the current version of our monitoring interface, the counters get disaggregated.

We are hoping to fix this issue in the near future.

In the meantime:
* You could fix this by inserting an extra groupbykey before the writes (thus preventing fusion), however this will hurt the pipeline's latency and performance.
* Once the holiday weekend is over, and my colleagues are back at work, I may be able to provide you with another way to manually query the counters and add them up.
* Or of course, you could wait some time until we have the counters unified in the UI.

Sorry for the inconvenience!

Thanks,
Dan

**Comment by sduskis** [comment]
There's nothing for cloud bigtable to do here.  I'm going to close this.
