### ISSUE TITLE
no BigtableInstanceClient class exists in the 0.9.1 release

### ISSUE THREAD

**Issue by faizalkassamalisc** [GoogleCloudPlatform/cloud-bigtable-client#924]
This class [BigtableInstanceClient.java](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableInstanceClient.java) does not resolve in the [latest maven release 0.9.1](https://mvnrepository.com/artifact/com.google.cloud.bigtable/bigtable-client/0.9.1) although the previous BigtableClusterAdminClient [was removed](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/commit/d21c719ff93401fd183cb8bf16805c47e2adc0a8).  This makes it impossible to call [BigtableSession.getInstanceAdminClient()](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/c9bafc94b586bbc3e4406924fa72e0e7f8b924a2/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableSession.java#L344).

What are we supposed to do here?

**Comment by faizalkassamalisc** [comment]
^ @sduskis

**Comment by sduskis** [comment]
Sorry you're having troubles.  Can you please elaborate on the artifact you're downloading? I checked bigtable-hbase-1.1-0.9.1.jar in maven, and the BigtableInstanceClient was there.  

You referred to com.google.cloud.bigtable:bigtable-client which is our parent project, which is just a pom.xml, and wouldn't have any jar or classes associated with it.

**Comment by faizalkassamalisc** [comment]
Thanks @sduskis.  We just want the BigTable Client, not HBase and all the transitive dependencies it pulls in that conflict with our existing project dependencies.  What is the best way to get that?

**Comment by sduskis** [comment]
The [Bigtable Client Core](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22bigtable-client-core%22) the right artifacts.

Let's please speak offline.  I think that there may be some information that pertains to your company.  Please email the address on my github profile.  FYI, @gamorris, I believe this relates to you.

**Comment by sduskis** [comment]
new BigtableSession(bigtableOptions).getInstanceAdminClient() ought to work. 

I'm closing this issue, since there doesn't seem to be anything actionable on my end.  Please reopen if you feel we need to do more.
